### ISSUE TITLE
Support a custom function to load meta for routes

### ISSUE THREAD

**Issue by antfu** [hannoeru/vite-plugin-pages#1]
This could be useful for some sites like blogs to have the metadata over each post.

**Comment by hannoeru** [comment]
Sounds great, any idea how to implement it?
I think custom block like [vite-plugin-vue-i18n](https://github.com/intlify/vite-plugin-vue-i18n) will be good.

**Comment by antfu** [comment]
I am using markdown's frontmatter while I would need to have the posts list with some digests (title, desc, date, summary, etc). Using custom block might be useful but it might be a bit overkill while also make this plugin more coupled with Vue SFC.

I am thinking about something like this:

```js
import Pages from 'vite-plugin-pages'
import Markdown, { metaResovler } from 'vite-plugin-md'

export defualt {
  plugins: [
    Pages({
      extensions: ['vue', 'md'],
      async extendMeta(filepath, routepath) { // or ctx object
        if (filepath.endsWith('.md')
          return await metaResovler(filepath) // or a custom one
      }
    }),
    Markdown()
  ]
}

```

**Comment by hannoeru** [comment]
I think you can use `route.component`
```js
import Pages from 'vite-plugin-pages'
import Markdown, { metaResovler } from 'vite-plugin-md'

export defualt {
  plugins: [
    Pages({
      extensions: ['vue', 'md'],
      async extendMeta(route, parent) {
        if (route.component.endsWith('.md')
          return await metaResovler(filepath)
      }
    }),
    Markdown()
  ]
}
```

**Comment by antfu** [comment]
Oh wait, looks like I can use `extendRoute`. I will give it a shot!
