### ISSUE TITLE
Nested route with children (using React)

### ISSUE THREAD

**Issue by RicardoValero95** [hannoeru/vite-plugin-pages#102]
### Discussed in https://github.com/hannoeru/vite-plugin-pages/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **RicardoValero95** October  3, 2021</sup>
Hi, does anyone know how to have nested views with children? 

[Codesandbox](https://codesandbox.io/s/react-vite-pages-i16pg)

In the sandbox there's
- basic routing example **user** with **profile**, **login**, **logout**
- a nested view example **about** page
- a nested view with basic routing example **tabs** with **feed**, **chats**, **settings**

This last one is not working, I can't get to the children feed, chats or settings. If I remove the "layout" `tabs.tsx`, then navigation works fine (just like any other basic routing). 

Thanks in advance, great plugin 😄 
</div>

**Comment by ArcaneWizard** [comment]
If you want a better understanding of it, have you checked out the official react-router documentation? Specifically, the examples on URL parameters and nesting. They cover the concepts utilized in the sandbox above: https://reactrouter.com/web/example/nesting

**Comment by hannoeru** [comment]
We are moved to react-router v6, if you have any problem, please open a new issue.
