### ISSUE TITLE
Cannot detect pages from npm packages / node_modules

### ISSUE THREAD

**Issue by cimchd** [hannoeru/vite-plugin-pages#104]
I have a monorepo project and want to automatically detect pages from a private npm package. My vue project is a package itself. Here are simplified directory structure where I want to auto detect the pages from package `test-package` from inside `vue-project`.

```
/home/user/project-root
|-- node_modules
|-- packages
     |-- vue-project
     |   |-- pages
     |   └-- vite.config.ts
     └-- test-package
         └-- pages


```
In reality the project setup includes src/dist folders and the typical boilerplate code for vite and vue, I skipped that to keep this example simple.

This is what I have tried in the options (one after the other, not all at once):

```js
{
      pagesDir: [
        'pages',
        // import from node_modules 
        '../../../node_modules/test-package/pages',
        { dir: '../../../node_modules/test-package/pages', baseRoute: '' },
        // import by its package name
        '@project/test-package/pages',
        { dir: '@project/test-package/pages', baseRoute: '' },
        // import by monorepo path (just for test purpose, won't work in production)
        '../test-package/pages',
        { dir: '../test-package/pages', baseRoute: '' },
      ]
}
```
None of them worked. The error in the browser console was: 
`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://home/user/project-root/packages/test-package/pages/my-page.vue`

Is there already a way to configure this right? Or is this feature simply not supported?

**Comment by productdevbook** [comment]
some problem :/

**Comment by kissu** [comment]
Got this with the latest `v19.2`, downgrading to `v18.2` fixed the issue.

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?
