### ISSUE TITLE
Problem with nested routes for react router

### ISSUE THREAD

**Issue by zoubingwu** [hannoeru/vite-plugin-pages#106]
Trying to use this in a react project, not sure I'm doing it right.

File structure is like below:

```
src/pages/
  ├── index/
  │  ├── topics.tsx
  │  ├── test.tsx
  │  └── index.tsx
  └── index.tsx
```

What I want is to build a nested view under index route. The nav links always stays and only nested view changes when I click the links:

![image](https://user-images.githubusercontent.com/18644268/139250265-16010245-fcf1-496e-bef3-af359a5317e3.png)

![image](https://user-images.githubusercontent.com/18644268/139250359-57ac69d0-5704-431c-ae94-5ddf2da8b65b.png)

The problem is root level route object always have exact props as true, making it impossible to match other children routes. So I have to add following lines to workaround:

```diff
+ extendRoute(route, parent) {
+  if (route.routes && route.routes.length > 0) {
+    delete route.exact
+  }
+ }
```

also, the children route didn't have complete path, I have to manually fix it and check each child have their own children again to fix the `exact` status. This might can be done in the plugin to produce a correct route tree?

```diff
+ const child = route?.routes?.map(r => ({ 
+   ...r, 
+   path: `${route.path === '/' ? '' : route.path}${r.path}`,  
+   exact: r.path === '/' 
+ }))
```

reproduce repo is here: https://github.com/zoubingwu/vite-plugin-pages-nesting-routes.

codesandbox is [here](https://codesandbox.io/s/vite-plugin-pages-nesting-routes-3ss38?file=/src/pages/index.tsx)

**Comment by ArcaneWizard** [comment]
If I understand your problem correctly, this post has some potential solutions for that: https://stackoverflow.com/questions/52684017/react-router-v4-nested-match-params-not-accessible-at-root-level

**Comment by zoubingwu** [comment]
@ArcaneWizard There is a workaround I made in the repro repo, it's fully functional as expected.

It is not a problem of react-router side I think, there are still lots of work needs to be done in the plugin if it's gonna adopt react-router perfectly because of it's flexibility. I had some thoughts in my mind now, might send a pr when I have time to do it.

**Comment by zoubingwu** [comment]
for conveniece, added a [codesanbox link]( https://codesandbox.io/s/vite-plugin-pages-nesting-routes-3ss38?file=/src/pages/index.tsx), notice those workaround code lines were in src/pages/index.tsx and vite.config.ts

**Comment by hannoeru** [comment]
We are moved to react-router v6, if you have any problem, please open a new issue.
