### ISSUE TITLE
How to use vite-plugin-pages in multi-pages program？

### ISSUE THREAD

**Issue by grabbinits** [hannoeru/vite-plugin-pages#107]
I want to develop a multi-pages h5 and use this plugin, how should i do, thx

**Comment by hannoeru** [comment]
Can you provide more context?

**Comment by grabbinits** [comment]
@hannoeru 

I set multi-pages in rollup input config：

![image](https://user-images.githubusercontent.com/53926367/139640348-caf1fa5b-ba8f-41d3-b688-e16adb73879a.png)

![image](https://user-images.githubusercontent.com/53926367/139640157-d461c363-b134-45c7-bbf4-adc2e5a19478.png)

How to config vite-plugin-pages like this?
Thx very much!

**Comment by hannoeru** [comment]
Can you share this repo?
