### ISSUE TITLE
How to redirect to another path

### ISSUE THREAD

**Issue by hugohabicht01** [hannoeru/vite-plugin-pages#108]
Is it possible to define redirects an aliases like specified [here](https://next.router.vuejs.org/guide/essentials/redirect-and-alias.html#redirect)?
Or is the only way to redirect using router.replace on a page?

**Comment by hannoeru** [comment]
https://github.com/hannoeru/vite-plugin-pages#extendroute
https://github.com/hannoeru/vite-plugin-pages#sfc-custom-block-for-route-data

**Comment by Tsuyoshi84** [comment]
I set `vite.config.ts` like this, and it worked.

```typescript
    Pages({
      extensions: ['vue'],
      extendRoute: (route) => {
        // Redirect from '/' to '/xyz'
        if (route.path === '/') {
          return { ...route, redirect: 'xyz' }
        }

        return route
      },
    }),
```

**Comment by ArgekarStudios** [comment]
This is not redirecting but from root '/' redirecting
 Pages({
      extensions: ['vue'],
      extendRoute: (route) => {
        // Redirect from '/' to '/xyz'
        if (route.path === '/user') {
          return { ...route, redirect: '/user/profile' }
        }

        return route
      },
    }),

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by fabien-ml** [comment]
Hi, just found that using `route block` in your pages can do the trick.
In the example below `xyz` is the route name not path.

```jsx
// index.vue

<route lang="yaml">
redirect: xyz
</route>
```

**Comment by fabien-ml** [comment]
Hi, just found that using `route block` in your pages can do the trick.
In the example below `xyz` is the route name not path.

```jsx
// index.vue

<route lang="yaml">
redirect:
  name: xyz
</route>
```

**Comment by ArgekarStudios** [comment]
@fabien-ml  that worked thank you
