### ISSUE TITLE
parent route block not passed to children

### ISSUE THREAD

**Issue by castrix** [hannoeru/vite-plugin-pages#111]
so I make this routing `test-page/index.vue` and `test-page/child.vue`
I expect that route meta in `index.vue` to be passed to `child.vue` if `child.vue` didn't have `Route Data`

I set the route data in `index.vue` like this:
```
<route lang="yaml">
meta:
  isAuth: true
  role: ['admin', 'tes', 'user']
</route>
```

and it showed up in my views

but when i try to access `test-page/child` the route data is empty.

## ~~working in dynamic routing~~
~~the weird thing is that, if I use dynamic routing, the route data is passed to the children. I made a new folder path `home/index.vue` and `home/[id].vue`. this one work as expected, route data from the parent `index.vue` passed to the `[id].vue`~~

reproduce: https://github.com/castrix/fit-vue3-boilerplate

**Comment by castrix** [comment]
I found the workaround using `nested route` but I'm not a fan on how it's written, can you add some options to automatically created nested routes with this kind of file path

```
src/pages/
  ├── users/
  │  ├── child.vue
  │  └── index.vue
```
to generate:

```json5
[
  {
    path: '/users',
    component: '/src/pages/users.vue',
    children: [
      {
        path: '',
        component: '/src/pages/users/index.vue',
        name: 'users'
      },
      {
        path: ':id',
        component: '/src/pages/users/[id].vue',
        name: 'users-id'
      }
    ]
  }
]
```

**Comment by lennartzellmer** [comment]
Thanks for sharing your solution!

I just had the same issue when using folders and wanted to display the status on active links in my navigation. When using a structure like 

```
src/pages/
  └── users/
     ├── child.vue
     └── index.vue
```

I was not able to display the route as active. I had to add the "empty" nested route template to make it work.

```
<template>
  <router-view />
</template>
```

Just wanted to share another use case for having the Route Data present in these cases :)

Great project BTW! Love it!

**Comment by hannoeru** [comment]
That is how vue router works, we can’t wrap a nested route without the component.
