### ISSUE TITLE
VueRouter 3.0 Support?

### ISSUE THREAD

**Issue by zouhangwithsweet** [hannoeru/vite-plugin-pages#12]
Can I use Vue2.x + VueRouter3.x + vite-plugin-pages ?
Actually, I have tried it and it looks ok, but I don’t know if there are unpredictable bugs ^-^

**Comment by hannoeru** [comment]
Yes, the routes structure is basically the same, so it can adopt to vue-router v3.

**Comment by zouhangwithsweet** [comment]
> Yes, the routes structure is basically the same, so it can adopt to vue-router v3.

Nice work !!!

**Comment by Stvchm9703** [comment]
if it can, is there any example?
