### ISSUE TITLE
Do docs on importing ~pages module need to be updated?

### ISSUE THREAD

**Issue by mythz** [hannoeru/vite-plugin-pages#120]
The [docs say](https://github.com/hannoeru/vite-plugin-pages#vue-1) we need to import from the `~pages` module:

```csharp
import { createRouter } from "vue-router";
import routes from "~pages";

const router = createRouter({
  // ...
  routes,
});
```

However this resulted in an error in my Vite + Vue + TypeScript project:

```
TS2307: Cannot find module '~pages' or its corresponding type declarations.
```

Through some trial & error and self code discovery I finally found the correct module to import:

```ts
import routes from "pages-generated"
```

I can see in [client.d.ts](https://github.com/hannoeru/vite-plugin-pages/blob/main/client.d.ts) that it specifies `~pages`, `pages-generated` and `virtual:generated-pages`, what config or factors determines which of these options should be used?

**Comment by hannoeru** [comment]
`~pages` is only available in ^0.19.0, which is currently in beta.
type issue is fixed in beta.3

**Comment by mythz** [comment]
Ok thanks for the quick response, just updated to the beta and it works thx.

IMO since the docs are written for the beta (i.e. there are other issues like pagesDir vs pages) it should suggest to install the beta instead:

```
npm i -D vite-plugin-pages@beta
```

As following the docs will lead to issues that takes a long time to track down.

Great library BTW 👍

**Comment by softboy99** [comment]
~pages module  cannot be found aftet upate to 0.31 verson
