### ISSUE TITLE
Unable to fetch "_...all_" file

### ISSUE THREAD

**Issue by J-Human** [hannoeru/vite-plugin-pages#122]
Greetings. 

For context, I have a small Vue repository - https://github.com/J-Human/J-Human.github.io [^1]. I am positive that the problem is coming from this - https://github.com/J-Human/J-Human.github.io/commit/42aecc10dcc5f173aaea617cd3cb1207e2de451d. Ever since I updated vite-plugin-pages, it seems like it changes the ordinary [...all] file to `_...all_`, for example - https://github.com/J-Human/J-Human.github.io/commit/ceb5b41dcd18d173fc325a1a83e1384c803011e3. Then I found out there's this setting - replaceSquareBrackets. But! I found out it's false by default, so me setting it [to false] does not help. So, to the actual problem - whenever I deploy my page via GitHub Pages, and once I navigate to a random page, and once I go to the dev tools, it says the all file cannot be requested (404). I'm not talking about GHPs' default 404 page, since I have a 404.html file, I'm just not sure why it automatically made it a underscore-prefixed/suffixed file. I might be a bit dumb here.

Any sort of nudge to the right direction is welcomed!

[^1]: Live site is over here: https://J-Human.github.io.

**Comment by hannoeru** [comment]
Just checked it, filename with square brackets is not replaced by this plugin, if you create a pure `create-vite-app` project then try something like `[filename].js` it will still replace `[]` to `_`, so I think I can remove that option.

I have no idea about 404 issue, this work fine on my side using Netlify, maybe is some limitation about GitHub Page in file naming.

**Comment by J-Human** [comment]
> Just checked it, filename with square brackets is not replaced by this plugin, if you create a pure `create-vite-app` project then try something like `[filename].js` it will still replace `[]` to `_`, so I think I can remove that option.
> 
> I have no idea about 404 issue, this work fine on my side using Netlify, maybe is some limitation about GitHub Page in file naming.

OK, thank you for your kind clarification. As for the second point, I'll try to investigate. For now I'll close this issue.

**Comment by J-Human** [comment]
For anyone that stumbles over this issue, the solution to stop GHP from blocking files with underscore-prefixes, simply create an empty `.nojekyll` file in the root of your publish directory/branch.
