### ISSUE TITLE
Error: No match for

### ISSUE THREAD

**Issue by productdevbook** [hannoeru/vite-plugin-pages#129]
``` 
<router-link :to="{name: 'aa-slug', params: {slug: '1231512'}}" class="text-sm font-medium">test</router-link>
```
          
pages/aa/[slug].vue

console.log
No match for
 {"name":"aa-slug","params":{"slug":"1231512"}}
 
 "vite-plugin-pages": "0.19.0-beta.6",
   "vue-router": "4.0.12",

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by productdevbook** [comment]
looks like there is no problem now
