### ISSUE TITLE
weird alphabetical ignore error

### ISSUE THREAD

**Issue by JonasKruckenberg** [hannoeru/vite-plugin-pages#13]
So I've been wrangling this problem a lot today, but I think I got it nailed down now.
The steps to reproduce are as follows:
1. add a index.vue file that has `<route>` block that sets a custom name that is the same(?!!) as the filename.
2. add files that come before 'index' (so starting with a etc.)
3. add files that come after 'index' (like starting with z)
4. only the files that come before 'index' get generated routes.

Things to note:
- This also triggers some sort of cache thing, HMR caches older version sometimes
- once you remove the name attribute from the `<route>` block everything works again
- the file gets recognized so it's not an globbing issue

I don't think this issue is particularly devastating but it's sooooo weird and so perplexing that I had to share it! 🤣

**Comment by hannoeru** [comment]
Can't repro, can you provide a example? and also the version you are using and OS info, thanks.

**Comment by JonasKruckenberg** [comment]
To be honest I couldn't, and besides, the issue is so niche and weird that it's alright to close it for now i think 👍🏻
