### ISSUE TITLE
get router in js/ts file

### ISSUE THREAD

**Issue by nshusr** [hannoeru/vite-plugin-pages#130]
get router in js/ts file

useRouter in file get undefined

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by nshusr** [comment]
@hannoeru 
What I want to ask is, how can I use router.push in addition to Vue components. I tried useRouter but it returned undefined

**Comment by productdevbook** [comment]
@nshusr 

add `import router from '~/router'` your router.ts with router.push etc used.`

**Comment by wishinghand** [comment]
@productdevbook or @reaink Could you show a code snippet of how you accomplished this? I don't quite follow what to do.

**Comment by reaink** [comment]
@wishinghand https://github.com/antfu/vite-ssg/issues/146#issuecomment-1000111177
