### ISSUE TITLE
Cannot find type definition file for 'vite-plugin-pages/client'

### ISSUE THREAD

**Issue by MichealPearce** [hannoeru/vite-plugin-pages#134]
Really not sure what's going on here. Been using this plugin for weeks with no issue but today I opened it with no changes and I'm getting an error in my `tsconfig.json` and where I'm importing `generated:routes` for missing type definitions. At first it was only happening in my freshly setup codespace, but now has popped up in all setups. 

Unfortunately I'm not able to share my setup currently, but after some debugging I was able to find two ways to correct the issue:
- remove `vite-plugin-pages/client` from `compilerOptions.types` and add `./node_modules/vite-plugin-pages/client.d.ts` to the `includes` option.
- remove the `exports` property from `vite-plugin-pages`'s `package.json` here:
https://github.com/hannoeru/vite-plugin-pages/blob/main/package.json#L17-L29

The first option is what I'm going for now since it's not a temporary patch that would be removed. If anyone know's what's happening or needs more info from me, just let me know. I'm also using yarn workspaces but from what I could tell that has no effect over the issue. 

Node: v14.18.2
Yarn: v1.22.15

```
"dependencies": {
	"@vueuse/head": "^0.7.2",
	"dayjs": "^1.10.7",
	"vite-ssr": "^0.14.3",
	"vue": "^3.2.16",
	"vue-router": "4"
},
"devDependencies": {
	"@vitejs/plugin-vue": "^1.9.3",
	"fibers": "^5.0.0",
	"npm-run-all": "^4.1.5",
	"sass": "^1.43.5",
	"typescript": "^4.4.3",
	"unplugin-vue-components": "^0.17.2",
	"vite": "^2.6.4",
	"vite-plugin-pages": "^0.18.2",
	"vite-plugin-vue-layouts": "^0.5.0",
	"vue-tsc": "^0.3.0"
}
```

**Comment by hannoeru** [comment]
Try upgrade to typescript 4.5

https://github.com/hannoeru/vite-plugin-pages/issues/118

**Comment by MichealPearce** [comment]
Looks like that might have fixed it, thank you kindly @hannoeru

**Comment by maietta** [comment]
> 

This did not work for me in Sept 2022.

**Comment by maietta** [comment]
I really wish I could figure out the edge-case problems I keep running into.

I'm running "typescript": "^4.8.4" and STILL having issues with Typescript reporting this error.
