### ISSUE TITLE
Dynamic nested routes generates double params

### ISSUE THREAD

**Issue by ChrisGV04** [hannoeru/vite-plugin-pages#135]
I have a project with a dynamic page that also uses nested pages to simulate tabs. This is the file structure:

```
src/pages/schools
  ├── [schoolId]/
  │  ├── main.vue
  │  ├── availability.vue
  │  └── schedule.vue
  ├── [schoolId].vue
  └── index.vue

```

And when I'm viewing the "main" page for a school, I expect the generated route path to be: `/schools/:schoolId/main`, but ever since I updated to version 0.19.3 the output is `/schools/:schoolId/:schoolId/main`.

I checked the generated router paths and it is adding the dynamic param to te parent route and also to it's children routes, which was not happening on version 0.19.2 with the exact same file structure. This is the output I'm getting on version 0.19.3:

```
...
{
  path: "/schools/:schoolId"
  children: [
    {
      path: "/:schoolId/main"
    }
    ...
  ]
}
...
```

And this is the expected output that was working perfectly on 0.19.2 and prior:

```
...
{
  path: "/schools/:schoolId"
  children: [
    {
      path: "/main"
    }
    ...
  ]
}
...
```

I hope this can be solved easily! Thank you.

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by ChrisGV04** [comment]
> Can you provide a repo with the code required to reproduce this issue?

Unfortunately I can’t share the real project where I encountered the issue. However, I created a small demo repo where the error also occurs. https://github.com/ChrisGV04/pages-issue

I hope it’s useful

**Comment by ChrisGV04** [comment]
Amazing! Now in 0.19.4 everything seems to be working as expected. 👍🏼
Thank you very much for your quick support and for making this awesome plugin!

**Comment by omnjpa27516** [comment]
@ChrisGV04 Could you please tell me how to output all the generated routes?

**Comment by ChrisGV04** [comment]
@omnjpa27516 Sure. I used the `onRoutesGenerated` config option inside the Vite plugin configuration for Pages(), which is a method that includes the routes as a parameter.

You can check it out  [on the docs](https://github.com/hannoeru/vite-plugin-pages#onroutesgenerated)

**Comment by omnjpa27516** [comment]
@ChrisGV04 Thank you so much!
