### ISSUE TITLE
error: Cannot read properties of null (reading 'parent')

### ISSUE THREAD

**Issue by mesqueeb** [hannoeru/vite-plugin-pages#137]
I just can't seem to get it to work. I'm using `0.19.5`

issue 1:
> Argument of type 'Router' is not assignable to parameter of type 'Plugin_2'.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/3253920/146645842-cbc0438f-9684-425a-8e6f-fd19382fe3e2.png">

issue 2:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/3253920/146645879-d7734c04-6226-410a-a32e-af1f28cfce09.png">

my `router.ts`:
```ts
/// <reference types="vite-plugin-pages/client" />

import { createRouter, createWebHistory } from 'vue-router'
import routes from '~pages'

export const router = createRouter({
  history: createWebHistory(),
  routes,
})
```

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by mesqueeb** [comment]
@hannoeru Good morning : )

 it seems to be something related to my monorepo setup. I am gonna try and find the cause and report back here.

**Comment by mesqueeb** [comment]
@hannoeru sorry for the false alarm! It worked when I deleted `package-lock.json` of the monorepo and reinstalled all packages!
