### ISSUE TITLE
Cannot find path '/'

### ISSUE THREAD

**Issue by snaplesec** [hannoeru/vite-plugin-pages#14]
I used import routes from 'pages-generated' 
and set that in the createRouter(), but cannot find path for '/'
How to set that for /home?
Also getting these in the console.  Not sure why.
[Vue Router warn]: No match found for location with path "/"
[Vue Router warn]: No match found for location with path "/"
[Vue Router warn]: No match found for location with path "/about"
[Vue Router warn]: No match found for location with path "/dashboard"
[Vue Router warn]: No match found for location with path "/login"
[Vue Router warn]: No match found for location with path "/dashboardinsuredportal"

BTW: great plugin, it works wonders, but just need to know how to set the path for  '/'

**Comment by hannoeru** [comment]
Can you provide a repro?

**Comment by snaplesec** [comment]
Hi,
yes, here is a link to code in my repo.
https://github.com/snaplesec/vite-plugin-pages-routing

**Comment by hannoeru** [comment]
Except missing some image, it works as expect, no vue router warning.
To set default to home page, just rename `index.vue` to `home.vue`,
then push the redirect route to routes like what you are doing now.

**Comment by snaplesec** [comment]
Thank you.  I will change that.  This is a great plugin for vite.
