### ISSUE TITLE
Route generation is incorrect

### ISSUE THREAD

**Issue by Soya-xy** [hannoeru/vite-plugin-pages#146]
When you create multiple [... all].vue files in different directories, the plugin randomly generates only one directory route and one directory route is missing

eg:
<img width="1572" alt="WeChat9ce50bb8a299c82a30f69e2e27f4653a" src="https://user-images.githubusercontent.com/56671014/148188452-071aecac-f5ec-4302-b4c3-227fe6a4a7d1.png">

**Comment by hannoeru** [comment]
There is a lot of priority issue so we only support one cache all route for now, but maybe we can add support for multiple cache all route in the feature.

**Comment by hannoeru** [comment]
Let's move to #136
