### ISSUE TITLE
[questions] xml extension exclude on route detection

### ISSUE THREAD

**Issue by jbaubree** [hannoeru/vite-plugin-pages#148]
Hi,

First, of all, thanks a lot for this work, this plugin is just amazing.
I have setup this plugin with a src/pages/[...all].vue and this work perfectly.
I want to add a sitemap file and get it on https://myurl.com/sitemap.xml so i have just put the sitemap.xml in my public folder.

When i run my project in local like Vitesse project https://github.com/antfu/vitesse (thanks to @antfu for this work), i can go on localhost:3333/sitemap.xml and i get my sitemap as expected. 
When i build this project with vite-ssg and i run builded project, i just get the 404 page from src/pages/[...all].vue when i go on https://mybuildedapp.com/sitemap.xml.

Is there any way to get my .xml file with builded app?

**Comment by hannoeru** [comment]
How do you serve dist folder? using vite preview or something else?

**Comment by jbaubree** [comment]
I have tried to copy my dist folder on my server, and with vite preview, in both cases i get the 404 page

**Comment by jbaubree** [comment]
With multiple tries, i can get xml file on my server when i refresh without cache...

**Comment by hannoeru** [comment]
Oh… I think that is service worker’s issue, you can check vite-plugin-pwa’s issue to find more details.

**Comment by jbaubree** [comment]
Thanks a lot, i will check that 😁

**Comment by jbaubree** [comment]
FYI, i fixed this issue by adding 'sitemap.xml' in VitePWA includeAssets option
