### ISSUE TITLE
[question] Sitemap generation

### ISSUE THREAD

**Issue by jbaubree** [hannoeru/vite-plugin-pages#149]
Hi there,

I'm interesting in add a sitemap to my vite app. I did some research and i didn't find anything to do generate one on a vite project.
I have forker your awesome pages plugin project and i added this feature.
Are you interesting on any PR to add this feature for all?

Best regards

**Comment by hannoeru** [comment]
I'm not sure about this, did you think pages plugin should include sitemap generate function? or we can provide some api that other plugin can get generated routes.

FYI: https://github.com/windicss/vite-plugin-windicss/blob/01b533bf8a7f417e086222a31691ccd609b74c7b/packages/vite-plugin-windicss/src/index.ts#L58-L64

**Comment by jbaubree** [comment]
Mmh i think both things can be good. A simple option to provide sitemap with a few code lines using sitemap.js https://github.com/ekalinin/sitemap.js can not be a possibility in your believe?

an example of sitemap option can be this :

export interface SitemapOptions {
  enabled?: boolean
  hostname?: string
  filename?: string
  dest?: string
  changefreq?: string
  priority?: number
  lastmod?: Date
}

**Comment by jbaubree** [comment]
To add one more thing, sitemap generator need to get nuxtStyle variable and use isDynamicRoute() util.

**Comment by hannoeru** [comment]
For simple usage, I think onRoutesGenerated hooks is enough for generate sitemap.
For more advance usage I think is better to create a vite plugin for sitemap, like what https://sitemap.nuxtjs.org/usage/hooks is doing, then in this plugin we can provide a API that other plugins can access generated routes.

**Comment by jbaubree** [comment]
Right, so you think you can provide an API with generated routes on your plugin? This will be amazing

**Comment by jbaubree** [comment]
Oh sorry, i didn't saw that onRoutesGenerated hook is already available. Thanks

**Comment by idesignzone** [comment]
> Hi there,
> 
> I'm interesting in add a sitemap to my vite app. I did some research and i didn't find anything to do generate one on a vite project. I have forker your awesome pages plugin project and i added this feature. Are you interesting on any PR to add this feature for all?
> 
> Best regards

Could you please share your solution?

**Comment by jbaubree** [comment]
@idesignzone I have made my solution working on my own project. I will make a real plugin for you tomorrow.

**Comment by jbaubree** [comment]
@idesignzone https://github.com/jbaubree/vite-plugin-pages-sitemap
