### ISSUE TITLE
How to handle multi entry apps

### ISSUE THREAD

**Issue by StephenStrickland** [hannoeru/vite-plugin-pages#15]
Hello, love the work you've done with this package. 

Does this plugin support multi page apps as documented [here](https://vitejs.dev/guide/build.html#multi-page-app) in Vite's docs?

If I have 3 entries, could I structure my files similar to the following
```
/root
   /app1
      /pages
   /app2
      /pages
   /app3
      /pages
```

**Comment by hannoeru** [comment]
Nope, in that case I think is better to separate the apps then use proxy to combine it.
Or try this one https://github.com/hannoeru/vite-pages

**Comment by TobiasSN** [comment]
Hey there, I had the same problem, and I solved it by adding this to the plugin's config:
```js
{
  pagesDir: fs.readdirSync("root").map(name => ({
    dir: `root/${name}/pages`,
    baseRoute: name
  }))
}
```
You need to make sure to import the `fs` module.
