### ISSUE TITLE
Are the generated routes case insensitive？

### ISSUE THREAD

**Issue by southwhale** [hannoeru/vite-plugin-pages#153]
example：
my pages like below：
```
---pages
 ｜---cleanTool
     ｜--- index.jsx
```

the generated routes is `/cleantool`, but I hope it is `/cleanTool`.
is there any option to resolve the problem.

**Comment by hannoeru** [comment]
Yes, currently all route will be transform to lowercase.
There is no options for this, PR welcome.

**Comment by jbaubree** [comment]
@southwhale Pull request has been merged, you will be able to use case sensitive routes in next release :)

**Comment by softboy99** [comment]
doesn't work, although set in vite.config.ts:
    Pages({
      dirs: [
        { dir: 'src/views', baseRoute: '' },
      ],
      extensions: ['vue', 'ts'],
      resolver: 'vue',
      moduleId: '~pages',
      caseSensitive: false,
    }),

Currently all route cannot be equal to vue-router.locatio.name
