### ISSUE TITLE
Custom Resolvers

### ISSUE THREAD

**Issue by N0tExisting** [hannoeru/vite-plugin-pages#156]
This is a very useful plugin, but I would like to be able to have my own resolver, when wanting to make custom routes, for eg. an api.

This would probably also help with #83.

**Comment by delaneyj** [comment]
I also have the same issue... specifically the vite dev server can proxy/route `/api/*` to `localhost:1234` but if you use a catch all you don't get hits to that api server when in production build.  In my case I'd like to have a way to turn off the catch all specifically for `/api*` routes.

**Comment by N0tExisting** [comment]
@delaneyj I just want to generate routes for my server (I'm trying to do SSR)

**Comment by Jordan-Hall** [comment]
I'll take a look at this. I'm working with Vite and Angular so it be great to support custom resolver

**Comment by hannoeru** [comment]
We will support custom resolver from v0.23.0, currently in beta.

Resolver's interface:
https://github.com/hannoeru/vite-plugin-pages/blob/e1496e02e003ca0a70b31a7a87e2c1ed4e2e2c99/src/types.ts#L18-L32
