### ISSUE TITLE
configResolved build error

### ISSUE THREAD

**Issue by bkoplin** [hannoeru/vite-plugin-pages#158]
Hope I don't duplicate any other issues. On `vite build`, the `i.name.includes` here generates an error. Revising to `i.name?.includes` successfully builds…

https://github.com/hannoeru/vite-plugin-pages/blob/9611c78e012dc4d1051e93906ec942fcb9d95b1c/src/index.ts#L17

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?
