### ISSUE TITLE
Escape or replace square brackets in file names?

### ISSUE THREAD

**Issue by thalesagapito** [hannoeru/vite-plugin-pages#16]
Like with the nuxt routing module, the generation of routes with square brackets makes the plugin unusable in aws API Gateway environments. Original issue for reference: https://github.com/nuxt/nuxt.js/issues/7625.

The problem is that API Gateway does not consider urls with square brackets valid, which makes dynamic and catch-all route files throw errors when loaded. Is there any way to replace these on build?
For now, I believe a workaround is to remove the brackets manually inside the dist folder, but ideally the plugin could have a way ty prevent this problem.

**Comment by frandiox** [comment]
@thalesagapito Hey, did you find this error when using `vite-ssr` or Nuxt?

**Comment by thalesagapito** [comment]
I was using vite-ssr, I just mentioned the nuxt issue because the nuxt team has faced the same problem before. Sorry if I wasn't clear.

**Comment by hannoeru** [comment]
@thalesagapito from v0.4.9 I set replaceSquareBrackets to false by default because it will break dynamic pages, you can manually set it to true to enable replacement.

**Comment by hannoeru** [comment]
From v0.5.0 replace square brackets should also works in dynamic pages with replaceSquareBrackets option set to true.
