### ISSUE TITLE
Deep work[or replace] with vite-plugin-layout

### ISSUE THREAD

**Issue by fyeeme** [hannoeru/vite-plugin-pages#164]
Most of the cases, we use layout for a group of route placed in some folders. so is it possible to work with them like this to avoid use custom block <router>

the new layout api is similar to `dirs` api
add `layouts ` params

```js
export default {
  plugins: [
    Pages({
      dirs: [
        { dir: "src/pages", baseRoute: "" },
        { dir: "src/features/**/pages", baseRoute: "features" },
        { dir: "src/admin/pages", baseRoute: "admin" },
      ],
      layouts: [
        { dir: "src/pages", layout:  "src/layouts/default.vue" }, // this can be  set by defualt .
        { dir: "src/features/**/pages", layout: "src/layouts/feature.vue" },
        { dir: "src/blank/pages", layout: "src/layouts/blank.vue" },
      ],
    }),
  ],
};
 
```

@hannoeru

**Comment by yankeeinlondon** [comment]
I wonder if this is what has broken my home page working with this plugin and latest `vite-plugin-layouts`? I have already reverted the upgrade to _layouts_ but I jumped from 0.19 to 0.21 here and there are no change logs so it's a bit more work to understand what's happened.

**Comment by tsanyqudsi** [comment]
currently i use onRoutesGenerated options and write a new function 

you can see the example on https://github.com/luna-indonesia/cmfy/blob/main/workspaces/website/libs/setNewRoutes.ts

**Comment by hannoeru** [comment]
Out of scope
