### ISSUE TITLE
Regression: Square brackets in filename

### ISSUE THREAD

**Issue by frandiox** [hannoeru/vite-plugin-pages#17]
Hi! I'm having an error related to #16 using `0.4.7`. I'm trying to deploy to Cloudflare Workers and it works in `0.4.6 ` (it seems CF workers allow brackets in the filenames), so I guess this is a regression issue.

I have a route `/hi/:name` (like in Vitesse) and the build outputs a file `dist/client/assets/_name_.0441a72a.js` for that one. There's no file with brackets. However, another JS file is trying to import the following:

```js
component:()=>Mt((()=>__import__("./[name].0441a72a.js")),["/assets/_name_.0441a72a.js","/assets/vendor.2de24244.js"])
```

It is trying to request both, brackets and underscored versions:

![image](https://user-images.githubusercontent.com/1634092/109423738-04085b80-7a24-11eb-8eeb-8a1061377dc0.png)

I'll downgrade to 0.4.6 for now, which outputs the file with brackets only.

Thanks!

**Comment by hannoeru** [comment]
Can you provide a repro?

**Comment by tshemeng** [comment]
@frandiox since 0.4.6, you need add `replaceSquareBrackets: false` to `vite-plugin-pages` config,

example:
```json
    // https://github.com/hannoeru/vite-plugin-pages
    Pages({
      extensions: ['vue', 'md'],
      replaceSquareBrackets: false
    }),
```

**Comment by frandiox** [comment]
@tshemeng Ah I see, thanks!
In any case, I'll try to add a repro for the default case since I guess it shouldn't be requesting both...

**Comment by hannoeru** [comment]
I think replace square break dynamic routes so I will revert it now until I find a solution, you can upgrade to v0.4.8 and remove replaceSquareBrackets from options.
