### ISSUE TITLE
about [Vue Router warn]: No match found for location with path "/"  error message.

### ISSUE THREAD

**Issue by cibilex** [hannoeru/vite-plugin-pages#171]
I tried many ways but this package is not working for 2 days.Please help me
```typescript
// vite.config.ts
import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'
import Pages from 'vite-plugin-pages'

const config = defineConfig({
  plugins: [
    Vue(),
    Pages(),
  ],
})
export default config
```

```typescript
// src/main.ts
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import App from './App.vue'
import routes from '~pages'
// also import routes from "virtual:generated-pages" not working.

console.log(routes) // []
const router = createRouter({
  history: createWebHistory(),
  routes,
})

const app = createApp(App)
app.use(router)
app.mount('#app')
```
pages structure : 
```
    pages
            index.vue
```
and when I run the project this error throw  :  
```bash
vue-router.esm-bundler.js:72 [Vue Router warn]: No match found for location with path "/"
```
Dependencies:
```typescript
  "dependencies": {
    "install": "^0.13.0",
    "vue": "^3.2.31",
    "vue-router": "^4.0.12"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^2.2.0",
    "@vue/compiler-sfc": "^3.2.31",
    "cross-env": "^7.0.3",
    "typescript": "^4.5.5",
    "vite": "^2.8.4",
    "vite-plugin-pages": "^0.20.2"
  }
```

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by cibilex** [comment]
https://github.com/cibilex/vite-plugin-pages-err 
@hannoeru

**Comment by hannoeru** [comment]
I still can't reproduce this warning, can you try again, or give me more details?

**Comment by hannoeru** [comment]
Can you provide some system info by running `npx envinfo --system --binaries --browsers`?

**Comment by cibilex** [comment]
```bash
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 807.21 MB / 7.85 GB
  Binaries:
    Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 3.0.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.55)
    Internet Explorer: 11.0.19041.1202
```

**Comment by cibilex** [comment]
My problem has been solved.My opinion :
- Might be originated from "vite-plugin-vue".Yesterday they have updated "vite-plugin-vue" and my codes are working now.

Anyway,thanks a lot @hannoeru  to help me.

**Comment by AxelConceicao** [comment]
I had the same issue, I just removed node_modules and pnpm-lock and it works now after reinstalling everything

**Comment by lvsong77** [comment]
Sorry to reply on this closed issue, but I have the same issue found in my computer.
I just cloned the [https://github.com/antfu/vitesse](vitesse) repo, and in my computer I see this warn
```
[Vue Router warn]: No match found for location with path "/"
```
the rest route works fine except the 'index.vue'

but I have tried this repo in github codespace, and it works fine.
I don't know if there is some problem with my computer environment...

below is my computer info:
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 807.21 MB / 7.85 GB
  Binaries:
    Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 3.0.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.55)
    Internet Explorer: 11.0.19041.1202
```

looking for help. @hannoeru

**Comment by lvsong77** [comment]
> Sorry to reply on this closed issue, but I have the same issue found in my computer. I just cloned the [https://github.com/antfu/vitesse](vitesse) repo, and in my computer I see this warn
> 
> ```
> [Vue Router warn]: No match found for location with path "/"
> ```
> 
> the rest route works fine except the 'index.vue'
> 
> but I have tried this repo in github codespace and other computer, and it works fine. I don't know if there is some wrong with my computer environment...
> 
> below is my computer info:
> 
> ```
>   System:
>     OS: Windows 10 10.0.19043
>     CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
>     Memory: 807.21 MB / 7.85 GB
>   Binaries:
>     Node: 16.14.0 - D:\Program Files\nodejs\node.EXE
>     Yarn: 3.0.2 - ~\AppData\Roaming\npm\yarn.CMD
>     npm: 8.1.3 - D:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.55)
>     Internet Explorer: 11.0.19041.1202
> ```
> 
> looking for help. @hannoeru

It's strange when I add `exclude: ['**/comps/*.vue']` to the Page conifg in `vite.config.ts`, the problem gone away.
before:
```
    Pages({
      extensions: ['vue', 'md'],
    }),
```
after:
```
    Pages({
      extensions: ['vue', 'md'],
      exclude: ['**/comps/*.vue']
    }),
```

I cannot understand whte happened.
@hannoeru
