### ISSUE TITLE
`~solid-pages` import not working on `Solid JS`

### ISSUE THREAD

**Issue by Netherlander** [hannoeru/vite-plugin-pages#173]
When I tried to import this plugin into a Solid JS project, I ran into a problem - the path `~solid-pages` was not visible and gave an error. However, according to one guide for version 0.18.2, I found a solution to this problem. Instead of `~solid-pages` when importing, it was necessary to write `virtual:generated-pages`. This solved my problem.
In this regard, please tell me, is it just that the imports have not been changed since the last version or is there an error in the documentation?

**Comment by hannoeru** [comment]
What version are you using? Solid JS support is only available in beta channel for now.

**Comment by Netherlander** [comment]
I'm using latest - 0.20.2.

**Comment by Netherlander** [comment]
Even with a directive `/// <reference types="vite-plugin-pages/client-solid" />` the working path is still the same - `virtual:generated-pages`

**Comment by hannoeru** [comment]
That is not beta version, use `npm install -D vite-plugin-pages@beta` to install beta version.

**Comment by Netherlander** [comment]
Ok, thanks. Now both methods work.
