### ISSUE TITLE
Route type ?

### ISSUE THREAD

**Issue by tsanyqudsi** [hannoeru/vite-plugin-pages#182]
in Readme.MD it's explained the type of routes generated from onRoutesGenerated is `Route[ ]`,

https://github.com/hannoeru/vite-plugin-pages/blob/c26a177d163129f6175bc95fe5a2b9073dabac1b/README.md?plain=1#L337

However, when I write the code, it's `any[ ]`.

Is it a glitch or there's something should be done ? if it's should be `Route` instead of `any`.. should this package export the type ?

**Comment by hannoeru** [comment]
Current we can't support all types from different frameworks,  instead we exports the route type that you can import and use it manually.
