### ISSUE TITLE
Handle localisation segment optionally existing in path

### ISSUE THREAD

**Issue by dewelooper** [hannoeru/vite-plugin-pages#183]
Hello,
I would like to ask you Guys if there is some way to handle optional localisation segment in url. I mean something like that:

domain.com/feature
domain.com/de/feature
domain.com/au/feature

all these routs should open the same component.

I tried to figure out it somehow but without any results. Possible or not?

Thank you!

**Comment by hannoeru** [comment]
I think you can add some logic on onRoutesGenerated to resolve localization routes.

**Comment by dewelooper** [comment]
> I think you can add some logic on onRoutesGenerated to resolve localization routes.

Perfect solution!

Thank you:)
