### ISSUE TITLE
routes from subdirectory getting overridden if file with the same name exists

### ISSUE THREAD

**Issue by laylatichy** [hannoeru/vite-plugin-pages#184]
so I was trying to do nested routes as in the example in the readme [link](https://github.com/hannoeru/vite-plugin-pages#nested-routes)

src/pages/
  ├── users/
  │  ├── [id].vue
  │  └── index.vue
  └── users.vue
  
  but content from files: [id].vue and index.vue is overridden by content from users.vue
  
  expected behaviour
/users -> users.vue (or /users/index.vue? as the docs are not clear)
/users/{id} -> users/[id].vue 

current behaviour
/users -> users.vue
/users/{id} -> users.vue 
  
  replication: https://stackblitz.com/edit/vitejs-vite-7bt4up?file=src/App.vue

**Comment by hannoeru** [comment]
That will become a nested route, if you only want this two route (`/users`& `/users/{id}`), just remove `users.vue` from your `src/pages` folder.

FYI: https://router.vuejs.org/guide/essentials/nested-routes.html
