### ISSUE TITLE
Association with vite-plugin-voie

### ISSUE THREAD

**Issue by chojnicki** [hannoeru/vite-plugin-pages#19]
I can see that both this and voie plugins are doing same thing - auto generating routes. So I though they are "competitors" to each other, fine.

But here at the bottom of Readme I see:

> See more details: vite-plugin-voie

I though maybe it works on top of voie, but I do not see it in dependencies. So maybe it is fork of voie (if yes, what idea was behind it)? Could be this clarified to help choosing right package? Thanks :)

**Comment by hannoeru** [comment]
Yes, this is a fork of Voie,
but with more feature like route block inside SFC, also can set multiple dir pagesDir option.
Voie is not updating since 9 Jan, it also can't works in Vite's SSR mode, so I made this plugin.
