### ISSUE TITLE
wildcard router

### ISSUE THREAD

**Issue by myNameCao** [hannoeru/vite-plugin-pages#191]
I like this pligin very much  it save me a lot of time 

but. i want to  creat wildcard router

for example  

```js
{
    path: '/app/*',
    name: 'app',
    meta: { title: '', requireAuth: false },
    component: () => import('@view/common/app.vue')
  }
```

`/app/a` or  `/app/a/b` and `/app/a/b/c`      them can  map to this page 

thanks

**Comment by hannoeru** [comment]
https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route
https://router.vuejs.org/guide/essentials/route-matching-syntax.html#repeatable-params

**Comment by myNameCao** [comment]
thank you. it already work
