### ISSUE TITLE
How to list pages from specific dir? 

### ISSUE THREAD

**Issue by imShara** [hannoeru/vite-plugin-pages#204]
I have pages in `/news` directory on  semi-static website, How can I list this pages?

I can list routes via

```
<router-link
  v-for="route in $router.options.routes"
  :key="route.path"
  :to="route.path"
>
  {{ route.name }}
</router-link>
```

but

1. Can't access metadata
2. Should filter results

**Comment by hannoeru** [comment]
Example:

https://github.com/hannoeru/hannoeru.me

Get metadata part is in vite's config file. And list post is in `src/components`.
