### ISSUE TITLE
Issue reseting password after deploying to firebase

### ISSUE THREAD

**Issue by qdubois** [hannoeru/vite-plugin-pages#206]
Hello,

I'm using firebase to deploy my vue 3 with **vite-plugin-pages**. 
When trying to reset the password using firebase there is a generated link  that looks like that :https//ww.myapp.com/__/auth/action?mode=resetPassword***

I get a 404 when opening the page.

Is there anything that i can do to bypass the route check?

thanks a lot

Quentin

**Comment by chipowok** [comment]
up

**Comment by hannoeru** [comment]
Normally when we use SPA you should redirect all path to `index.html`, that is the problem. so you should set redirect all path except `/__/auth` path in your web server settings.
