### ISSUE TITLE
Static site generation?

### ISSUE THREAD

**Issue by dolsem** [hannoeru/vite-plugin-pages#222]
The plugin works well in development, but `yarn build` produces a single page app. Is there a way to generate static HTML for any page, so that I can deploy it as a static website?

**Comment by hannoeru** [comment]
You can checkout antfu's [vite-ssg](https://github.com/antfu/vite-ssg) which works great with this plugin.

**Comment by dolsem** [comment]
@hannoeru can I use that with SolidJS? They only have instructions for Vue.

**Comment by hannoeru** [comment]
No, I vite-ssg is Vue only. Maybe you will need to write your own server side code to use SSG
in SoildJS.
