### ISSUE TITLE
Combination of index route and dynamic route doesn't seem to get resolved properly

### ISSUE THREAD

**Issue by bux** [hannoeru/vite-plugin-pages#23]
![image](https://user-images.githubusercontent.com/1235520/111209526-69378180-85cc-11eb-94e9-a5cbbc9e7ccc.png)

With the above setup of pages, when calling `localhost:3000/menuplan/` it seems that the dynamic route is being used instead of the index route.

Am I doing something wrong here?

Version: 0.7.0

**Comment by hannoeru** [comment]
It should works, can you provide more context?
or try to upgrade `vue-router` to latest version.

**Comment by bux** [comment]
A simple repro would be:

* Clone vitesse (or create a new github project by using this template)
* Create a new vue file below `~/src/pages/hi` and call it `index.vue`
* Add a `<template/>` with some demo content
* Run `npm run dev`
* Try to open: http://localhost:3333/hi/

Observe how the dynamic route is being used instead of the newly created index route

**Comment by hannoeru** [comment]
That is `vite-plugin-vue-layouts`'s bug, the work around for now is:
```ts
// add to main.ts
routes[0].children.forEach((i: any) => {
  i.path = i.path.substring(1)
  if (i.path.endsWith('?'))
    i.path = i.path.slice(0, -1)
})
```
Cc @JohnCampionJr

**Comment by bux** [comment]
Thank you. This has worked. Do you want me to open an issue on `vite-plugin-vue-layouts`'s repo?

**Comment by hannoeru** [comment]
Ok, then I will close this one.

**Comment by shroudedcode** [comment]
I'm also running into this issue and I'm **not** using `vite-plugin-vue-layouts`.

My `pages` directory looks like this:

```
├── [...notfound].vue
├── things
│   ├── [thing].vue
│   └── index.vue
└── index.vue
```

And these are my generated routes:

```js
[
  { name": "notfound", "path": "/:notfound(.*)" },
  { "name": "index", "path": "/" },
  // This route is always being matched:
  { "name": "things-thing", "path": "/things/:thing?" },
  { "name": "things", path": "/things" }
]
```

**Comment by hannoeru** [comment]
Optional parameters is removed from v0.9.0

**Comment by shroudedcode** [comment]
The new version fixed it. Thanks a lot for this great package, @hannoeru! :green_heart:
