### ISSUE TITLE
Dynamic route with . (dot) does not work

### ISSUE THREAD

**Issue by marwanpro** [hannoeru/vite-plugin-pages#232]
Hello,

The following structure doesn't not work when you input URL in the address bar:

    /
    +-pages
     +- versions/
       +- [ver].vue

On `router.push(/versions/02.00.00)`, it works.

however if I input http://127.0.0.1:3000/versions/02.00.00 in address page or I refresh the page, I have a black page.

If I input http://127.0.0.1:3000/versions/02 in address bar it works.

Have you any clues ?

**Comment by jbaubree** [comment]
Try this --> https://www.npmjs.com/package/vite-plugin-rewrite-all

**Comment by hannoeru** [comment]
Looks like this is a problem with `vue-router`, is better to open issue there instead of here, I will close this for now.
