### ISSUE TITLE
Error in esm project with v0.24.0

### ISSUE THREAD

**Issue by cimchd** [hannoeru/vite-plugin-pages#237]
After upgrading to v0.24.0 in an esm project ("type": "module" in package.json) the following error occurs:

```
failed to load config from /path/to/vite.config.ts
error when starting dev server:
Error: Dynamic require of "extract-comments" is not supported
[...]
```
After downgrading to v0.23.0 everything works again.

**Comment by coderzhaoziwei** [comment]
I met the same problem.
