### ISSUE TITLE
caseSensitive: false: the generated routes are not transformed to lowercase any more

### ISSUE THREAD

**Issue by softboy99** [hannoeru/vite-plugin-pages#239]
doesn't work, although set in vite.config.ts:
Pages({
dirs: [
{ dir: 'src/views', baseRoute: '' },
],
extensions: ['vue', 'ts'],
resolver: 'vue',
moduleId: '~pages',
caseSensitive: false,
}),

caseSensitive: false: the generated routes are not transformed to lowercase any more

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by softboy99** [comment]
sorry, my code is very large and can't push here.
![image](https://user-images.githubusercontent.com/228731/174276415-f53360ea-6b0c-45ec-934e-21077c0e05f8.png)


![image](https://user-images.githubusercontent.com/228731/174276334-0b5e832b-664a-497d-a477-7ada0f1069e7.png)

![image](https://user-images.githubusercontent.com/228731/174276236-b906f62b-5390-44aa-a652-f4fe3bc6a80b.png)

**Comment by hannoeru** [comment]
Looks normal to me.
When `caseSensitive === false`, we only change path to lower case, and keep route name the same as file name.

**Comment by softboy99** [comment]
from the above graph, the"matcheMap" keys are not changed to lower case
https://user-images.githubusercontent.com/228731/174276236-b906f62b-5390-44aa-a652-f4fe3bc6a80b.png
