### ISSUE TITLE
Are there plans to support _id.vue like nuxtjs

### ISSUE THREAD

**Issue by fulus06** [hannoeru/vite-plugin-pages#25]
Are there plans to support _id.vue like nuxtjs

![image](https://user-images.githubusercontent.com/12890684/112111461-2f2f3680-8bef-11eb-8bcb-b48f69ffbabd.png)

**Comment by hannoeru** [comment]
You mean the syntax or function? we already have dynamic route support: https://github.com/hannoeru/vite-plugin-pages#dynamic-routes

**Comment by fulus06** [comment]
I need to be compatible with part of the NuxtJS project。

**Dynamic routes are denoted using underline.
src/pages/users/_id.vue -> /users/:id (/users/one)
src/_user/settings.vue -> /:user/settings (/one/settings)**



If you don't have a plan, I'll just fork a copy of the code to make the changes

**Comment by hannoeru** [comment]
From v0.8.0, you can use `nuxtStyle: true` option to enable Nuxt.js style dynamic routing.

**Comment by praburangki** [comment]
But isn't nuxt v3 will change their syntax to use the brackets notation?
