### ISSUE TITLE
BUG REPORT: need await for extendRoute

### ISSUE THREAD

**Issue by YunYouJun** [hannoeru/vite-plugin-pages#257]
https://github.com/hannoeru/vite-plugin-pages/blob/97e01b1bbbe0d79486626e9fc679e6d0f34ed35e/src/resolvers/vue.ts#L57

When `extendRoute` is a `async function`, we need `await` for it.

**Comment by hannoeru** [comment]
Currently the `extendRoute` is not a `async function`, you can open a new issue for request this feature.

https://github.com/hannoeru/vite-plugin-pages/blob/c895f27385b52a1ab145fa1c8369329c61777ba2/src/types.ts#L108

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/178940494-366ea0dc-0c25-44ec-b658-7f95da1c0ed6.png)

I see you wrote it with the `async` example in #1.
So I guess this is a behavior that would have been implemented, right?
