### ISSUE TITLE
Always got warning when save source code on example/react in this project 

### ISSUE THREAD

**Issue by karnzx** [hannoeru/vite-plugin-pages#264]
![Screenshot 2022-07-26 234944](https://user-images.githubusercontent.com/26167071/181065808-d93c915a-b62a-4c63-a1cc-8c85bb0d665c.png)

First I clone the project and run dev on example/react but when I save the source code I always got this warnings 
"**Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.**"

**Comment by hannoeru** [comment]
Can not reproduce this error, fell free to reopen this.
