### ISSUE TITLE
[question] Cannot find module 'virtual:generated-pages' or its corresponding type declarations

### ISSUE THREAD

**Issue by mariusa** [hannoeru/vite-plugin-pages#27]
Hi, thanks for this great plugin!

In `main.ts` I get
```
Cannot find module 'virtual:generated-pages' or its corresponding type declarations
```
on the line `import routes from 'virtual:generated-pages'` (in vscode)

I see the module is declared at https://github.com/hannoeru/vite-plugin-pages/blob/main/client.d.ts
Is there something else to do in order to recognize that definition and rid of this error?

vite.config.ts
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import Pages from 'vite-plugin-pages'
import Layouts from 'vite-plugin-vue-layouts'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [vue(), Pages(), Layouts()]
})
```

**Comment by hannoeru** [comment]
<img width="530" alt="スクリーンショット 2021-03-28 4 19 05" src="https://user-images.githubusercontent.com/16288797/112732345-bdebdc80-8f7c-11eb-9496-dba9b4bd228b.png">

It works, can you provide more context?

**Comment by mariusa** [comment]
Hi, the same repro.zip attached at https://github.com/hannoeru/vite-plugin-pages/issues/28

![2021-03-28_12-42](https://user-images.githubusercontent.com/1283842/112748241-2fe71480-8fc3-11eb-8445-55c40956ca9a.png)


If it works for you, then it's something missing in my vscode setup, right?

**Comment by hannoeru** [comment]
Can you try [this setting](https://github.com/antfu/vitesse/blob/master/.vscode/settings.json) from [vitesse](https://github.com/antfu/vitesse)?

**Comment by mariusa** [comment]
I did. I also tried the entire vitesse project and installed Volar extension too. Same warning, on these modules

![2021-03-28_16-39](https://user-images.githubusercontent.com/1283842/112754358-62553980-8fe4-11eb-80d9-24a6ba32571a.png)

Appreciate your help on this. I don't want to waste your time, it's a minor issue. Closing, thanks for confirming it works for you.

**Comment by matthbe** [comment]
I was having the same issue. Turns out I was missing `"vite-plugin-pages/client"` in the types array in `tsconfig.json`.

**Comment by mariusa** [comment]
That solved it, thanks!

**Comment by jellykaiser** [comment]
> That solved it, thanks!

how to solve this ?

**Comment by ansidev** [comment]
@hannoeru The documentation is not clear.
```
// vite-env.d.ts
/// <reference types="vite-plugin-pages/client" />
```

By default, people will assume that the file `vite-env.d.ts` is located at root project, but it must be located under folder `src`. You must/should update the documentation to give exact file path for each new file.

**Comment by hannoeru** [comment]
@ansidev PR welcome, what you said depends on your `tsconfig.json`, if you included it, it should work.

**Comment by ansidev** [comment]
> @ansidev PR welcome, what you said depends on your `tsconfig.json`, if you included it, it should work.

@hannoeru I didn't said. It's simple, so I think you can do it!

**Comment by abitwhy** [comment]
> > That solved it, thanks!
> 
> how to solve this ?

You can refer to [vite client-types](https://vitejs.dev/guide/features.html#client-types).
If you're free, just look at theses terms: [reference types](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-path-), [compilerOptions.types](https://www.typescriptlang.org/tsconfig#types).

**Comment by maietta** [comment]
> I was having the same issue. Turns out I was missing `"vite-plugin-pages/client"` in the types array in `tsconfig.json`.

That did not work for me! :(

**Comment by gymcoding** [comment]
@ansidev 
I solved it by adding the code below. thank you
`/// <reference types="vite-plugin-pages/client" />
/// <reference types="vite-plugin-vue-layouts/client" />`

**Comment by Clickadelic** [comment]
It's 2024 and I'm getting this issue with my Vite setup. What is the current status of this? Anybody?

I can't get layouts to work and must use vite (cannot use Nuxt).

**Comment by ansidev** [comment]
@Clickadelic You should read previous comments. Hope they will help you to resolve your issue!
