### ISSUE TITLE
Remove `**/__*__/**` from ignore

### ISSUE THREAD

**Issue by ThaDaVos** [hannoeru/vite-plugin-pages#274]
### Describe the bug

I am setting up a template for future projects in our collection repo - the folder is called `__template__` as we always do with template repo's

After digging for ours I find the following line in your code, which most definitely will explain why I cannot get the routes to load:
https://github.com/hannoeru/vite-plugin-pages/blob/885484f30eec4feb50a09d44df32805e5d897fbd/src/files.ts#L8-L10

Is there a way to remove this from the ignore, or override it please?

### Reproduction

Can't really set one up as it's due to folder name down the path

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz
    Memory: 9.77 GB / 23.47 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 8.18.0 - ~/n/bin/npm
  Browsers:
    Firefox: 103.0
```

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ThaDaVos** [comment]
Is it released also? Just asking to be sure because then I can remove the bash file I used to change it inside the library

**Comment by hannoeru** [comment]
Not yet, wait next release.
