### ISSUE TITLE
adding module.exports in vite.config.js breaks   virtual:generated-pages

### ISSUE THREAD

**Issue by mariusa** [hannoeru/vite-plugin-pages#28]
` virtual:generated-pages` works fine until adding this to vite.config.js

```
const path = require('path')

module.exports = {
    alias: {
        // alias a path to a fs directory
        // the key must start and end with a slash
        '/@/': path.resolve(__dirname, 'src')
    },
}
```

```
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  virtual:generated-pages (imported by /home/marius/work/wensia/admin/src/main.ts)

Are they installed?
    at optimizeDeps (/home/marius/work/wensia/admin/node_modules/vite/dist/node/chunks/dep-0776dd57.js:65459:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOptimize (/home/marius/work/wensia/admin/node_modules/vite/dist/node/chunks/dep-0776dd57.js:69211:48)
    at async Server.httpServer.listen (/home/marius/work/wensia/admin/node_modules/vite/dist/node/chunks/dep-0776dd57.js:69225:17)
```

Would you have any suggestion on how to fix this? Thanks

**Comment by hannoeru** [comment]
Just try it and it works, can you provide more context? or a minimal reproduction will be great.
Also, `alias` option is moved to `resolve.alias`, and `path.resolve(__dirname, 'src')` is not end with slash so you need to remove slash from the end of `'/@/'`, otherwise you will need to write something like this: `/@//your-path`.

**Comment by mariusa** [comment]
Sure, thanks for looking into this! I've fixed the 2 points you raised.

This is using vue3 and gives the same error:
[repro.zip](https://github.com/hannoeru/vite-plugin-pages/files/6216152/repro.zip)

My other project is with vue2 and vite.

**Comment by hannoeru** [comment]
You can't use `module.exports` and `export default` in the same time...
the error message is because you didn't write vite config currently,
go to vite discord's #help channel https://chat.vitejs.dev/, they will help you.

**Comment by mariusa** [comment]
Thanks for looking.
