### ISSUE TITLE
MD file routing configuration

### ISSUE THREAD

**Issue by itmanyong** [hannoeru/vite-plugin-pages#283]
### Description

You can configure the route information such as meta and PATH in the MD file, just like the route content in the. Vue file.
For example, 1: the /about route generated by about. MD, however, cannot be configured with a valid layout attribute. As a result, the layout of all MD routes is the default layout.

### Suggested solution

You are advised to set the --********-- header of MD files to meta by default or set meta fields separately to provide meta values

### Additional context

![image](https://user-images.githubusercontent.com/53500371/187147850-053ec28c-7f22-45f1-9417-37d4a24da2ce.png)

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
This is out of scope of this project, so I will close this issue.

But you can still get those route info by using `extendRoute` option. [example](https://github.com/antfu/antfu.me/blob/5f0b8441d0edd3d0fa464802a41af3b1fffbabc5/vite.config.ts#L45-L59)
