### ISSUE TITLE
SFC custom block for Route Data not working in vue2.7+vue-router3

### ISSUE THREAD

**Issue by Bob0911** [hannoeru/vite-plugin-pages#293]
### Describe the bug

i created a new vue2.7 project use 
npm create vue@2
ts yes
jsx yes
vue-router yes
pinia yes
vitest yes
cypress no 
eslint yes
pretter

add vite-plugin-pages
add a custom route block on HomeView.vue
import routes from ~pages  with no meta info
i console log the routes and no meta 
![image](https://user-images.githubusercontent.com/22430053/191186688-8b95b98f-ed74-4319-ac22-0647f9168438.png)
![image](https://user-images.githubusercontent.com/22430053/191186765-52b32782-e534-44b9-9145-f02efad70b46.png)
![image](https://user-images.githubusercontent.com/22430053/191186869-6eb02ff2-06f5-42b9-8f0a-6296481704e5.png)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ayqmq7?file=.vscode/extensions.json

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 4.11 GB / 7.36 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kelsos** [comment]
@Bob0911 did you find a solution? or gave up? :)

**Comment by Bob0911** [comment]
@kelsos  :)

it is because my `@vue/compiler-sfc` is v2.7.10  the parse api has changed in v3+  
I edit  `/src/customBlock.ts`
```
41    return parse(code, {
42      pad: 'space',
43    }).descriptor
```
 to 
```
    return parse(code, {
      pad: 'space',
    }).descriptor || 
    (parse as any)({ 
      source:code
    })
```
and it works

**Comment by lyric-zemin** [comment]
@Bob0911 Can you submit the code ?
