### ISSUE TITLE
An example with authentication

### ISSUE THREAD

**Issue by blurdylan** [hannoeru/vite-plugin-pages#30]
I'd love to have an example with authentication, where the routes are accessible only with a particular variable being set to true.

I've added `requiresAuth: true` as meta, however I still can't force redirection from an unauthenticated route or apply my route guards based on a variable.

**Comment by replygirl** [comment]
+1

**Comment by hannoeru** [comment]
Check: https://next.router.vuejs.org/guide/advanced/navigation-guards.html

```ts
router.beforeResolve((to, from) => {
  if (to.meta.requiresAuth && ! isAuthenticated) {
    // do something
  }
})
```
 PR welcome 😊

**Comment by jordypereira** [comment]
Hello, where is the best place to put this Navigation Guard?

**Comment by bekjon-me** [comment]
> Check: https://next.router.vuejs.org/guide/advanced/navigation-guards.html
> 
> ```ts
> router.beforeResolve((to, from) => {
>   if (to.meta.requiresAuth && ! isAuthenticated) {
>     // do something
>   }
> })
> ```
> 
> PR welcome blush

this is not understandable enough.!!!!
