### ISSUE TITLE
error: [vite:dep-pre-bundle] Failed to resolve entry for package "@vue/runtime-dom".

### ISSUE THREAD

**Issue by fulus06** [hannoeru/vite-plugin-pages#31]
same issue：https://github.com/vitejs/vite/issues/2883

win10
node 14.15.3
pnpm 6.0.0

`npm run example:dev`

 error: [vite:dep-pre-bundle] Failed to resolve entry for package "@vue/runtime-dom".
![image](https://user-images.githubusercontent.com/12890684/113714553-18263380-971b-11eb-9c2d-572d070dca0f.png)

**Comment by hannoeru** [comment]
In pnpm v6 it use # in folder name, vite will get confuse with that, keep track on vitejs/vite#2883, will close this one because it's not related to this repo.
