### ISSUE TITLE
Can custom blocks infer types from RouteRecordRaw interface?

### ISSUE THREAD

**Issue by jdz321** [hannoeru/vite-plugin-pages#312]
I define my own route-meta type by extending RouteMeta interface of vue-router, it works fine in the traditional way of route definition, but there is no type checking and intellisense in custom blocks.

**Comment by kingyue737** [comment]
Hi, I just made a volar plugin for intellisense in custom block. Maybe you can try it and give some feedback

**Comment by jdz321** [comment]
It seems to be out of scope.
