### ISSUE TITLE
Unexpected path name when using `page.tsx` as extension

### ISSUE THREAD

**Issue by andrioid** [hannoeru/vite-plugin-pages#319]
### Describe the bug

I'm using this wonderful plugin for a React SPA, but I want my `pages/feature/` directory to contain feature specific components without turning every single one into a page.

So, I setup vite-plugin-pages with the following:

```
    Pages({
      dirs: [{ dir: "pages", baseRoute: "" }],
      extensions: ["page.tsx"],
    }),
```

It picks up the `feature/index.page.tsx` just fine. Except it doesn't strip the entire extension away from the path name. I'd expect path to be `feature`, but instead it's `feature.page`

In the StackBlitz, check the console for the app route line. It should match `index.page.tsx` (and it does), but the path name is incorrect `index.page`.

Is this intended behaviour, and if so; is there any of fulfilling my use-case of adding a postfix to the page routes, so that not all components are picked up by the plugin?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-b4bobc?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.29 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.1
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hannoeru** [comment]
That is how Node resolve extension, if you want to use something like `.page.tsx` try to use glob pattern in [`dirs`](https://github.com/hannoeru/vite-plugin-pages#dirs) option.

**Comment by andrioid** [comment]
AFAIK, the glob pattern in dirs only matches directories.

```
pages/users/index.page.tsx (page, should match users/)
pages/users/user-header.tsx (not a page, ignored)
pages/users/[id].page.tsx (page, should match users/123)
```

I thought `exclude` could help me, but I'd need to a negative RegExp pattern to exclude everything but "page.tsx" and still then the path would still resolve to `index.page`.

I just (incorrectly) assumed, that if we were to define our own extensions, then they would be stripped from the path.

I'll probably end up doing the following with an exclude glob:
```
pages/users/index.tsx (page, users/)
pages/users/cmp/user-header.tsx (component, ignored)
pages/index.tsx (page /)
```

Would there be any interest of changing this behaviour, so that user-defined, matched extensions are always stripped from the path?

In any case. Thanks for time and work.

**Comment by q1uxu** [comment]
My solution: 
```typescript
Pages({
  dirs: [{ dir: 'src/pages', baseRoute: '/', filePatern: '**/*.page.*' }],
  extensions: ['page.tsx', 'page.jsx', 'page.ts', 'page.js'],
  onRoutesGenerated: async (routes) => {
    function removePageSuffix(routes) {
      for (let route of routes) {
        if (route.path.endsWith('.page')) {
          route.path = route.path.slice(0, -5)
        }
        if (route.children) {
          removePageSuffix(route.children)
        }
      }
    }
    removePageSuffix(routes)
    return routes
  },
}),
```

**Comment by q1uxu** [comment]
Anyway, I hope vite-plugin-pages can work like next.js [pageExtensions](https://nextjs.org/docs/pages/api-reference/next-config-js/pageExtensions#including-non-page-files-in-the-pages-directory), unneed manul write onRoutesGenerated.
