### ISSUE TITLE
No way to generate routes for testing

### ISSUE THREAD

**Issue by fcortes** [hannoeru/vite-plugin-pages#32]
I've been trying for a while to create a router in a test context with the generated routes from the plugin but everything I have tried has failed.

I tried to use the `generateRoutes` in `generate.ts` but it seems that the function is not exported in the global module so no luck there.
Next I initialized the vite plugin as the normal build process would, thinking that somewhere a `routes` variable would be available, but after playing with it for a while I only ended up with a string containing the javascript definition of the routes (which I am assuming vite injects somewhere in the final bundle).
I tried using eval with the string but as there are `import`s for the components it wouldn't work with a "Cannot use import statement outside a module" error. I tried using node modules and compiling the source code, but I'm getting a bunch of other errors.

At this point I feel I'm fighting with the tools and libraries so I'm not sure if I'm doing something horribly wrong, misunderstanding how routes should be tested or the library is missing some useful functions for this.

For context, this is my last version of a `loadRouter.ts` file that I'm trying to use in tests as 
```js
import { loadRouter } from 'loadRouter'
beforeEach(loadRouter)
// ...tests
```

```ts
import pages from 'vite-plugin-pages'

export const loadRouter = async () => {
  const pagesPlugin = pages({ replaceSquareBackets: false, extensions: ['vue', 'md'] })
  // This feels wrong already
  const resolveId = (pagesPlugin.resolveId as any)('pages-generated', '', {})
  // The "as any" are because TS was freaking out with the optional resolveId and load functions
  const rawRoutes = await (pagesPlugin.load as any)(resolveId)
  const routes = eval(rawRoutes) // Fails as rawRoutes contains import statements
  // const routes = requreFromString(rawRoutes, '') // Fails with _compile function does not exist
  // ...Instantiate the router and return 
}

// I took this function from https://stackoverflow.com/a/17585470
// but I'm sure some of node's internals have changed. Anyway this feels too much for just loading the generated routes!
function requireFromString(src: string, filename: string) {
  const Module = module.constructor;
  const m = new Module()
  m._compile(src, filename) // Fails
  return m.exports
}
```

**Comment by hannoeru** [comment]
I don't know way you are testing this in node environment... but maybe this can help: https://stackoverflow.com/questions/57121467/import-a-module-from-string-variable

**Comment by fcortes** [comment]
How else do you suggest to test the application? I am trying to setup jest with vue-testing-library to do some basic integration tests. I could setup E2E testing with cypress or something like that but it seems overkill for my purposes. 
I ended up mocking the routes for each test with something similar to [this](https://github.com/testing-library/vue-testing-library/blob/3c33dc3dbae2098ec25fb8a0e515a67042be69df/src/__tests__/vue-router.js#L18) but I would've guessed there was a better way to set this up as routes are actually computed during build.

**Comment by hannoeru** [comment]
Since v0.9.3 generateRoutes will be exported.
