### ISSUE TITLE
[questions] i18n routes and sitemap.xml

### ISSUE THREAD

**Issue by stafyniaksacha** [hannoeru/vite-plugin-pages#33]
Hello ! 
First thanks for the work on this project :)

I'm just wondering if this plugin can handle generation of sitemap.xml file related to generated routes.
Also, it may be interesting to be able to localize URI per locale.

I think `<route>` SFC block is a good place for these settings.

I can start working on it, but I prefer to ask before as this plugin is growing :)

**Comment by hannoeru** [comment]
Sounds good, but this is a pages plugin, so I think create a new plugin to handle it will be better.
We can do something like [this](https://github.com/windicss/vite-plugin-windicss/blob/8b8073d6e806553139af01326a28679fdde0104a/packages/vite-plugin-windicss/src/index.ts#L40-L46) to get generated routes. WDYT

**Comment by stafyniaksacha** [comment]
Yes it is a better idea to externalize the sitemap generation with an exposed api :).

For the i18n routes, I like the [nuxt's behavior](https://i18n.nuxtjs.org/routing), but it means that vue-i18n is installed. Do you think this is a feature that this plugin can handle ?

**Comment by hannoeru** [comment]
This is out of scope of this plugin, but provide a resolver with some hooks this plugin have can make it works.
