### ISSUE TITLE
extendRoute does not support JS

### ISSUE THREAD

**Issue by blowsie** [hannoeru/vite-plugin-pages#338]
### Describe the bug

Since `yml` and `json5` don't allow us to write JS functions, I tried to extend a route using `  extendRoute`, however that fails when writing functions too.

**Config**
```
  extendRoute(route) {
          if (route.meta && route.meta.props) {
            route.props = function () {
              return route.meta.props
            }
          }
          return route
        },
```
**Output**
```
const __pages_import_0__ = ()=>import("/src/pages/test.vue");

const routes = [{
    "name": "test",
    "path": "/test",
    "component": __pages_import_0__,
    "props": function() {
        returnroute.meta.props;
    },
    "meta": {
        "title": "Item",
        "props": ["item", "delivery", "timeline"]
    }
}];

export default routes;
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zwtdaf?file=vite.config.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by blowsie** [comment]
also fails on `onRoutesGenerated`

```
   onRoutesGenerated(routes) {
          return routes.map((route) => {
            return {
              ...route,
              props: (to) => ({
                test: 'it',
              }),
            }
          })
        },
```

**Comment by blowsie** [comment]
Bug is [here ](https://github.com/hannoeru/vite-plugin-pages/blob/c52b2d9d39cd02b9972ea095b9e2a0508a647646/src/resolvers/vue.ts#L57)

[Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)
> The Object.assign() method copies all [enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable) [own properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn)

Functions are not enumerable, perhaps the code should spread here instead?

**Comment by hannoeru** [comment]
Because routes need to be serialize during build time then pass to frontend, so if you want to include some logic in props, try to extends routes in your entry point.
