### ISSUE TITLE
[Bugs] Cannot bind multiple baseRoutes to the same directory

### ISSUE THREAD

**Issue by censujiang** [hannoeru/vite-plugin-pages#349]
### Describe the bug

I want to make directories look like versions for a given language by pointing different baseRoutes to the same directory. This is done to allow the ViteSSG plugin to generate corresponding static web pages in different language directories, but it seems that the entire site cannot display pages. An example of error reporting:
```console
[Vue Router warn]: No match found for location with path "/"
```

### Reproduction

https://stackblitz.com/edit/github-2zsjpe

### System Info

```shell
[Vue Router warn]: No match found for location with path "/"
```

### Used Package Manager

yarn

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by censujiang** [comment]
@hannoeru @antfu  Are there any people?

**Comment by maxdiable** [comment]
hi,
i have same problem..
any solution ??

br
Max
