### ISSUE TITLE
How to add validation for the route

### ISSUE THREAD

**Issue by husayt** [hannoeru/vite-plugin-pages#35]
Thanks, for really useful and time saving plugin.

I have tried using it and stumbled upon one issue with validating dynamic routes.

Let's say I have a path `/[id]` where id is only valid for numbers below 100. For everything else I want it to go to catch all. Obviously I can use beforeRoute check. But I thought maybe there is a builtin solution. Also it needs to work  with SSG and to generate all the the pages /1, /2, ..., /100

Thanks in advance

**Comment by hannoeru** [comment]
Maybe this can help you: https://next.router.vuejs.org/guide/essentials/route-matching-syntax.html#custom-regexp-in-params

You can use [extendRoute](https://github.com/hannoeru/vite-plugin-pages#extendroute) to add RegExp to route path.

**Comment by husayt** [comment]
Just what was needed. Thanks
