### ISSUE TITLE
Is it possible to generate a typesafe route file?

### ISSUE THREAD

**Issue by rainmanhhh** [hannoeru/vite-plugin-pages#36]
add a script in package.json
```json
"scripts": {
  "generate-routes": "vite-plugin-pages generate"
}
```
everytime run the generate command, it recreates the route file (routes.ts)
```typescript
export const routes = {
  index: '#/',
  foo: {
    index: '#/foo',
    all: (p: unknown) => `#/foo/${p}`,
    bar: '#/foo/bar'
  }
}
```
then routing can be
```
import {routes} from './routes'

const Com = <div onClick={() =>history.push(routes.foo.index)}>go to foo</div>
```

**Comment by hannoeru** [comment]
I think use onClientGenerated hooks to generate a custom client code, with this feature: https://github.com/vuejs/vue-router-next/pull/872 can get typescript supported for route names.
