### ISSUE TITLE
Ability to store route info in SFC

### ISSUE THREAD

**Issue by JohnCampionJr** [hannoeru/vite-plugin-pages#4]
I have a PR coming shortly for this but wanted to open the issue for discussion.

I really like the auto route generation, but am not crazy about putting route info into vite.config.js

I like the solution provided by https://github.com/ktsn/vue-route-generator so I shamelessly used that as a reference for the changes made in the PR.   

Alternatively, I thought of taking a dependency on that and using it to do all of the route generation.  Upside would be it would be the same routes generated by vue-cli and vite. 

If you would rather go that route (and I think is a lot to be said for doing it that way) let me know and I'll work on it.

**Comment by JohnCampionJr** [comment]
Pushed an update that causes HMR on any change in the pages folder since the route blocks might be updated.  Thinking an option for this as it could get expensive with very large apps.  Let me know your thoughts

**Comment by hannoeru** [comment]
I prefer do something similar to vite-plugin-vue-i18n by resolve custom block in transform, that also can support hmr by default.

**Comment by JohnCampionJr** [comment]
Ok; that may be a bit above my skill level :).

**Comment by hannoeru** [comment]
I think you can still modify the routes from `pages-generation` import and add some meta, instead of writing it into the `vite.config.js` or you can create the other function to resolve extendRoute.
Hope that can help you.

Thanks for the PR.

**Comment by JohnCampionJr** [comment]
I'm no expert, and I certainly could be looking at this wrong, but I did take a look at vite-plugin-vue-i18n, and while I like the block parser provided by vite, and it works well there since it is on a file by file basis anyway.  

In this case, I'm not real clear on how you could use the transform since you would need to rebuild the entire router anyway to get it reloaded.  

Are you thinking of rebuilding the whole plugin to hold the initial file config around, update the transformed file in that config, regenerate the routes and send by HMR?

Just trying to learn :)

**Comment by hannoeru** [comment]
> Are you thinking of rebuilding the whole plugin to hold the initial file config around, update the transformed file in that config, regenerate the routes and send by HMR?

**Comment by JohnCampionJr** [comment]
So I felt like a challenge :). I couldn't get transform to work in conjunction with HMR so I tried a different approach.  

https://github.com/JohnCampionJr/vite-plugin-pages/tree/sfc-hmr

It does store the config and only updates what is needed during HMR.  It just happens in the HMR event and not transform.

**Comment by hannoeru** [comment]
I think there is a simple way to do that.

1. Compare the code inside custom block to decide HMR or not.
you don't need to `checkChildren(generatedRoutes, file)` in HMR because you still need to reload module, simply check is the code changed or not, then `return [module]` to emit HMR on `pages-generated`, I preferred generate a hash from the code inside custom block, save it in the Map with filePath as kay, then just compare hash to check is it changed or not.

2. When HMR emit, it will reload `pages-generated`, which will use transform function.
it means we can just regenerate the routes, don't need to save it.

**Comment by JohnCampionJr** [comment]
1. I thought we were trying to get away from re-reading all of the files every time the routes are generated. Also, The `checkChildren` is misnamed.  It's really finding the node that matches the file given.

2. At the point transform is called, its too late to resend the module.  That happens in load.  transform is called after load; I couldn't find a way to update the routes at that point.

**Comment by hannoeru** [comment]
Oh...you are right, I have no idea how to resolve this problem, so maybe we can just add a options to turn custom block function on or off, the simply reread all file on HMR.

**Comment by JohnCampionJr** [comment]
OK, I'll tidy it up tomorrow and send a new PR

**Comment by JohnCampionJr** [comment]
OK, I'm a little stuck.  I have it all working but the one piece I can't figure out is that the <router> block being left in the SFC seems to be confusing things.  It works fine if I do:

```js
<route lang="json">
{
  "meta": {"requiresAuth": true}
}
</route>
```

But take out the `lang="json"` and it breaks when vue-router tries to load the component

I've got a transform method that seems like it should be removing that but its not working.  Whenever you have a spare minute, can you take a look?

**Comment by JohnCampionJr** [comment]
I just changed the parser to JSON5 which is much easier on us humans to type and get right.

In case you're curious, this is what I'm trying to get to - layouts in Vitesse:
https://github.com/JohnCampionJr/vitesse/tree/layout

**Comment by hannoeru** [comment]
Can you put cwd into resolved options as `pagesDirPath`, and cut some main logic to separate files form `index.ts`?

**Comment by hannoeru** [comment]
And can you use `route.component` to find route to change? because `route.filename` is not include  in vue-router's `RouteRecordRaw` type.

**Comment by JohnCampionJr** [comment]
That's on the custom Route type, not the Vue RouteRecordRaw

**Comment by hannoeru** [comment]
Eventually routes will be used in vue-router, so `Route` need to be assignable to vue-router's route type `RouteRecordRaw`,  `Route`(with filename) type can not assign to `RouteRecordRaw`. so you need to use other way to check or remove the `filename` when you send it back.

**Comment by JohnCampionJr** [comment]
The only thing we get in HMR is the filename.  Multiple files can have the same name.   Names and Components don't necessarily match the file.  Not sure how else to do this.

**Comment by JohnCampionJr** [comment]
Other changes in PR submitted.

I understand what you're saying about filename, still trying to come up with a solution.
