### ISSUE TITLE
eslint import/no-unresolved; Unable to resolve path to module 'virtual:generated-pages'

### ISSUE THREAD

**Issue by MartinMa** [hannoeru/vite-plugin-pages#41]
ESLint complains about the line `import generatedRoutes from 'virtual:generated-pages';` with `Unable to resolve path to module 'virtual:generated-pages'`.

Any idea how I can make the linter happy?

I can only think of this:
```ts
// eslint-disable-next-line import/no-unresolved
import generatedRoutes from 'virtual:generated-pages';
```

Thanks.

**Comment by hannoeru** [comment]
Because it's a virtual module witch is not exits in file system, simply disable this rule, it will be fine.

**Comment by MartinMa** [comment]
Thanks, I disabled `import/no-unresolved` in `.eslintrc.js` for my project. Apart from that I noticed that `tsc` checks for problems with module resolutions as well and displays errors directly in the IDE of VS Code. So I will still catch this kind of errors.

**Comment by dhruvkb** [comment]
Instead of disabling the rule entirely, I found that ignoring the rule for virtual paths is also viable.

```js
// .eslintrc.js
module.exports = {
  // other config
  rules: {
    'import/no-unresolved': ['error', {
      ignore: ['^virtual:.*'],
    }],
  },
}
```
