### ISSUE TITLE
The field name "filePattern" in the config contains a spelling error.

### ISSUE THREAD

**Issue by gjfLeo** [hannoeru/vite-plugin-pages#418]
### Description

According to the README document, the "filePattern" field can be used in the "dirs" field of the config. However, this field is incorrectly named as "filePatern", resulting in the setting being invalid.

(I think this is a bug, but it may be more appropriate to use the "proposal" template. )

### Suggested solution

The correctly spelled "filePattern" field should be allowed to function properly.
Considering compatibility issues, perhaps the misspelled "filePatern" should also remain valid.

### Alternative

If "filePattern" is unable to function properly, the documentation should be amended.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
Fixed https://github.com/hannoeru/vite-plugin-pages/commit/633f54c49604578c5901ccde4b0ae21dd7552826, will be released at v0.30.0.
