### ISSUE TITLE
Vite5.0 support

### ISSUE THREAD

**Issue by srob-ntap** [hannoeru/vite-plugin-pages#445]
### Description

Unable to update my app to Vite5.0 due to pages plugin dependency.

```
3.309 npm ERR! While resolving: vite-plugin-pages@0.31.0
3.309 npm ERR! Found: vite@5.0.0
3.309 npm ERR! node_modules/vite
3.309 npm ERR!   dev vite@"5.0.0" from the root project
3.309 npm ERR!   peer vite@"^4.0.0 || ^5.0.0" from @vitejs/plugin-vue@4.5.0
3.309 npm ERR!   node_modules/@vitejs/plugin-vue
3.309 npm ERR!     dev @vitejs/plugin-vue@"4.5.0" from the root project
3.309 npm ERR!
3.309 npm ERR! Could not resolve dependency:
3.309 npm ERR! peer vite@"^2.0.0 || ^3.0.0-0 || ^4.0.0" from vite-plugin-pages@0.31.0
3.309 npm ERR! node_modules/vite-plugin-pages
3.309 npm ERR!   dev vite-plugin-pages@"0.31.0" from the root project
```

### Suggested solution

https://github.com/hannoeru/vite-plugin-pages/blob/main/package.json#L67

https://vitejs.dev/blog/announcing-vite5
https://vitejs.dev/guide/migration.html

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by PeterHewat** [comment]
GitHubs' [renovate ](https://github.com/apps/renovate) bot has already done the necessary. Check out the [PRs that are awaiting validation](https://github.com/hannoeru/vite-plugin-pages/pulls). But it seems this project hasn't receive much attention in the past 6 months.

**Comment by hannoeru** [comment]
Let's try v0.32.0-beta.0 works or not.

**Comment by hannoeru** [comment]
Check out v0.32.0
