### ISSUE TITLE
Can we expose `generateRoutes` and `generateClientCode`?

### ISSUE THREAD

**Issue by morelearn1990** [hannoeru/vite-plugin-pages#47]
I see that the plugin exposes the two functions `onRoutesGenerated` and `onClientGenerated`. Can we also expose `generateRoutes` and `generateClientCode`? I think it's much easier to customize the code directly than after the operation

**Comment by hannoeru** [comment]
Can you provide more context or example?

**Comment by morelearn1990** [comment]
For example, we can generate react routes through  custom `generateRoutes `。
Or we can filter some  js files that do not meet the component conditions
Or we can use plugins to process more files than router, such as automatically registering vuex

**Comment by morelearn1990** [comment]
Having said that, I think  if you have time, you can rewrite a plugin to process files and generate corresponding code, so that pages plugin can be based on this plugin。

Such a plugin is definitely needed by the community

**Comment by hannoeru** [comment]
I agree with add react routes support, but others is out of scope of this plugin.

**Comment by morelearn1990** [comment]
As you think, it's OK

**Comment by hannoeru** [comment]
React support is added in v0.11.0 as experimental feature.
