### ISSUE TITLE
react-router-dom dependency not needed

### ISSUE THREAD

**Issue by mariusa** [hannoeru/vite-plugin-pages#49]
Hi & thanks for this useful plugin!

Was wondering why `react-router-dom` is installed in our vue project which uses vite-plugin-pages
react-router-dom doesn't seem used, except in examples: https://github.com/hannoeru/vite-plugin-pages/search?q=react-router-dom
Would you please consider removing it from package.json? Each project can install their own desired framework/router.

Thanks!

**Comment by hannoeru** [comment]
Sorry is was a mistake, I will fixed it in next release.
