### ISSUE TITLE
[Feature Request] support convention layouts

### ISSUE THREAD

**Issue by liujiayii** [hannoeru/vite-plugin-pages#496]
### Description

The directory structure is as follows:
``` jsx
.
└── src
    ├── layouts
    │   └── index.tsx
    └── pages
        ├── index.tsx
        └── users.tsx
```
The following routes will be generated:
```jsx
[
  { 
    path: '/', 
    component: '@/layouts/index',
    routes: [
      { path: '', component: '@/pages/index' },
      { path: 'users', component: '@/pages/users' },
    ],
  },
]
```

### Suggested solution

none

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Jabberwocky238** [comment]
in version 0.32.3, i achieve this by accident
if it could help
`
.
└── src
    └── pages
        ├── user
            ├──index.vue
            ├──subpage2.vue
            ├──[which]
                ├──subsubpage.vue
        └── user.vue
`
The following routes will be generated:
`
[
  { 
    path: '/', 
    component: '@/pages/user.vue',
    routes: [
      { path: '', component: '@/pages/user/index.vue' },
      { path: 'subpage2', component: '@/pages/user/subpage2.vue' },
      { path: ':which/subsubpage', component: '@/pages/user/[which]/subsubpage.vue' },
    ],
  },
]
`

**Comment by hannoeru** [comment]
Out of scope
