### ISSUE TITLE
About the [...all].vue , get the wrong visit result.

### ISSUE THREAD

**Issue by chengpeiquan** [hannoeru/vite-plugin-pages#51]
Hi, this problem has bothered me for a while.

When the blog [https://chengpeiquan.com/](https://chengpeiquan.com/) has been visited, then, visit these static pages:

- [https://chengpeiquan.com/feed.xml](https://chengpeiquan.com/feed.xml)

- [https://chengpeiquan.com/feed.json](https://chengpeiquan.com/feed.json)

- [https://chengpeiquan.com/feed.atom](https://chengpeiquan.com/feed.atom)

They will enter the 404 page. (In other words, it is the [[...all].vue](https://github.com/chengpeiquan/chengpeiquan.com/blob/main/src/views/%5B...all%5D.vue) component)

But I use `curl` to check these file, they are OK.

```bash
# e.g.
curl https://chengpeiquan.com/feed.xml
```

They are also possible to use `Ctrl + F5` to visit the correct result.

In the [dist](https://github.com/chengpeiquan/chengpeiquan.com/tree/gh-pages) folder, these files are existed.

I don't quite understand why this happens.

**Comment by hannoeru** [comment]
Because service worker is serving that page from cache.
@userquin is this related to cache control in vite-plugin-pwa?

**Comment by chengpeiquan** [comment]
> @hannoeru yeah, seems to be related to the service worker, the plugin version is 0.5.2 (too old). This seems to be related with [Bust cache after a release](https://github.com/antfu/vite-plugin-pwa/issues/33).
> 
> @chengpeiquan upgrade `vite-plugin-pwa` to latest version (`0.7.3`) and review the options. Due to the amount of pages being cached, I suggest you to use `prompt for update` strategy. You can take a look at the new options, and for `prompt for update strategy` see the `examples/vue-router` example and how to integrate with you app: take a look at `examples/vue-router/src/ReloadPrompt.vue` component and its `vite.config.ts` file.
> 
> You can see this strategy in action on `vueuse` project (configured with `vitepress`), where the amount of pages is high and so the service worker does not interfere with the app.

Wow! Thank you very much! I tried to turn off the PWA plugin first, and found this problem was indeed caused by PWA, not with this pages plugin!

Then I upgraded the version of PWA and now the problem is solved! Thx! @userquin @hannoeru
