### ISSUE TITLE
Changing <route> isn't picked up

### ISSUE THREAD

**Issue by jods4** [hannoeru/vite-plugin-pages#52]
When modifying the `<route>` custom block of a page, the new information isn't available in the app even after a full reload.
It looks like the only way to see the changes is to restart Vite.

**Comment by hannoeru** [comment]
It works in my environment, can you provide more context?

**Comment by hannoeru** [comment]
Can you try v0.11.2 works or not?

**Comment by jods4** [comment]
I just tried 0.11.2 and it didn't work.

I'm on Windows, yes.

For example if I have a SFC with:
```html
<route>
name: abc
</route>
```

Then I see the generated routes in browser with `name: abc`, as expected.

Now in `dev` mode, if I change `name` to say `xyz`:
- I see Vite notices the changes and reloads the file;
- But the generated routes in browser stays `abc` until I restart Vite completely.

A similar issue is that if I add a `<route>` block to a file that has none, it isn't picked up either.

**Comment by hannoeru** [comment]
Just fixed another bug, can you try v0.11.3?

**Comment by jods4** [comment]
I tried 0.11.3.
Seems to work better, I can change some things such as the `path`.

But other changes are still not picked up.
I use `extendRoute()` option to change things based on properties I put in `<route>`. Is it called again with a fresh new route after a file change?
The changes I make in `extendRoute()` don't appear in front-end even after a full page refresh.

**Comment by hannoeru** [comment]
Oh... I got it, will fix it later.

**Comment by jods4** [comment]
@hannoeru I just tested 0.11.4 and can confirm it works 🎉 
It looks like every page / route / property updates correctly without restarting Vite now.

... but it also introduced a major regression, see #55  😢
