### ISSUE TITLE
Set beforeEnter in extendRoute

### ISSUE THREAD

**Issue by robheymann** [hannoeru/vite-plugin-pages#53]
Hi,

Thanks for the great component. 

I am new to vue and vite, and I am looking to set "route.beforeEnter: Auth0.routeGuard" in the Pages.extendRoute config in vite.config.ts (assuming this is the correct place for this)

Could you perhaps assist with how to get this done? Assume I need to access the RouteRecordRaw?

Many Thanks,
Rob

**Comment by hannoeru** [comment]
```
extendRoute(route, parent) {
  if (route.path === 'somePath') {
    return {
      ...route,
      beforeEnter: Auth0.routeGuard
    }
  }
},
```

**Comment by robheymann** [comment]
Thank you very much for the reply :)
