### ISSUE TITLE
Do nested routes have to use the same file as the directory name

### ISSUE THREAD

**Issue by awagege** [hannoeru/vite-plugin-pages#57]
In my system, there are a large number of pages of different categories that use the same layout component. I can put these different categories in the same directory and perform secondary classification, but this will cause more routing paths. A layout routing level.
Is there a way to point multiple directories to the same layout file?

**Comment by awagege** [comment]
Example:
```
src/pages/
  ├── dirA/
  │  └── index.vue
  ├── dirB/
  │  └── index.vue
  └── custom.vue

[
  {
    path: '/dirA',
    component: '/src/pages/custom.vue',
    children: [
     //...
    ]
  },
  {
    path: '/dirB',
    component: '/src/pages/custom.vue',
    children: [
     //...
    ]
  }
]
```

**Comment by hannoeru** [comment]
You can use vite-plugin-vue-layouts

**Comment by awagege** [comment]
Thank you, this plugin can solve my problem. I think there are a lot of people like me who have the need to write duplicate nested files in the page directory, so I recommend that you write this plug-in introduction in the README.
