### ISSUE TITLE
POST请求带query参数时，拦截不到请求

### ISSUE THREAD

**Issue by cxy930123** [hannoeru/vite-plugin-pages#58]
当post请求的url中带有query参数时，无法拦截请求，比如：

POST请求地址：`/api/files?lang=zh-CN`

mock文件：

```js
export default {
  url: '/api/files',
  response: {},    
}
```

结果并不能拦截到请求。如果去掉query部分就能拦截到，get请求无此问题。

**Comment by hannoeru** [comment]
Can you provide more context?

**Comment by cxy930123** [comment]
不好意思，提错地方了
