### ISSUE TITLE
When using plugin with React, peer dependencies related with Vue maybe not needed?

### ISSUE THREAD

**Issue by saintwinkle** [hannoeru/vite-plugin-pages#61]
Hi, I'm using this awesome plugin for a while in my React project. That's great!

When deploying to vercel.com, the missing peerDependencies (vue & @vue/compiler-sfc) will cause build errors. But I'm actually not using Vue stack at all. 😂 Now I add them to my devDenpendencies and everything works fine.

So I think we should cancel these two peer dependencies in package.json, or after the experimental?

**Comment by hannoeru** [comment]
Try new version.

**Comment by bramaudi** [comment]
If someone have same issue on new version try deleteing node_modules and re-installing all dependencies, this solved for me.
