### ISSUE TITLE
onMounted hook is not triggered when navigating through subpages

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [hannoeru/vite-plugin-pages#62]
I don't know whether it's a bug or intended behavior but when I try navigating through pages of a given route I don't get onMounted hook executed. E.g. my pages folder structure:
`pages/category/[name].vue`

if I try to navigate from `/category/1` to `category/2` onMounted() hook won't be executed
```
<template>
  <h1>Welcome to {{ props.name }} category</h1>
</template>

<script lang="ts" setup="props">
  import {ref, defineProps, onUpdated, onMounted} from 'vue'

  const props = defineProps({
    name: {
      type: String,
      required: true
    }
  })


  onMounted(() => {
     // This one won't execute
     console.log('Mounted')
  })

  onUpdated(() => {
    // This will be executed but might happen multiple times which is suboptimal
    console.log('Updated')
  })
</script>
```

**Comment by hannoeru** [comment]
Because it is using same component in dynamic route, so it only emit props update,
just replace `onMounted` to watch props then it should works.

**Comment by AndrewBogdanovTSS** [comment]
Yes, with watch it's working fine
