### ISSUE TITLE
Error when there's an "@" in the home directories name

### ISSUE THREAD

**Issue by Simonwep** [hannoeru/vite-plugin-pages#68]
First of all, thank you for this great plugin - it's awesome!

Between `v0.13.4` and `v0.14.0` you've made [this commit]([vite-plugin-pages/commit/0d19e689a4b7bda7ae4a5cc9efb50b3bcaf17270](https://github.com/hannoeru/vite-plugin-pages/commit/0d19e689a4b7bda7ae4a5cc9efb50b3bcaf17270)) which broke the code on my end. The problem is that there's an `@` sign in my home directory path (because we're using LDAP) which causes the following problem:

![image](https://user-images.githubusercontent.com/30767528/123794236-eae4be00-d8e2-11eb-8c1f-f757b0a32358.png)

Caused by the generated code:

```ts
import __home_xxx@xxx_index_vue from '//home/xxx/pages/index.vue'
//               ^ Invalid character

const routes = [...]

export default routes
```

I tried to find the corresponding code but without success - I guess it has something to do with how you resolve the module :/

Sorry that I can't give you a reproduction, I hoped that the problem is easy enough since it's the only fix import you have in there.  Ask me if you need anything else, I know that this is very specific but I guess a solution can be to just use fixed name for the import? (not sure where this is done though)

The only configuration I have is:

```ts
pagesDir: path.resolve(__dirname, './pages')
```

When using a relative path I'll get an empty array from 'virtual:generated-pages'.

**Comment by hannoeru** [comment]
pagesDir should be related to your root dir and not start with `/`, like `src/pages`.

**Comment by Simonwep** [comment]
Thank you for the super fast response!
The issue is that for some reason I'll get an empty array back if I use a relative path (that also worked with v0.13.4), my file structure is as follows:

```
/frontend/pages/...
/vite.config.ts
```
As vite-`root` I use `./frontend` and for `pagesDir` `pages` with 
* vite-plugin-pages: v0.14.4
* vite: v2.3.8

I also tried `./pages`, `./frontend/pages` without any luck :/

**Comment by hannoeru** [comment]
Can you run `DEBUG=vite-plugin-pages:* npm run dev` and see what path you get?

**Comment by hannoeru** [comment]
Try v0.14.5, should fixed it.

**Comment by Simonwep** [comment]
Just tried it with `v0.14.6` still no success (empty array) :/ I get the following for each `pagesDir`:

<summary>
<code>pagesDir: 'pages'</code>

<details><pre><code>
  vite-plugin-pages:options {
  vite-plugin-pages:options   pagesDir: [ { dir: 'pages', baseRoute: '' } ],
  vite-plugin-pages:options   routeBlockLang: 'json5',
  vite-plugin-pages:options   root: '/home/xxx@xxx/frontend',
  vite-plugin-pages:options   extensions: [ 'vue', 'ts', 'js' ],
  vite-plugin-pages:options   importMode: 'async',
  vite-plugin-pages:options   exclude: [],
  vite-plugin-pages:options   syncIndex: true,
  vite-plugin-pages:options   replaceSquareBrackets: false,
  vite-plugin-pages:options   nuxtStyle: false,
  vite-plugin-pages:options   react: false,
  vite-plugin-pages:options   extensionsRE: /\.(vue|ts|js)$/,
  vite-plugin-pages:options   extendRoute: undefined,
  vite-plugin-pages:options   onRoutesGenerated: undefined,
  vite-plugin-pages:options   onClientGenerated: undefined
  vite-plugin-pages:options } +0ms
  vite-plugin-pages:pages Map(0) {} +0ms

  vite v2.3.8 dev server running at:

  > Local: https://localhost:3000/
  > Network: use `--host` to expose

  ready in 707ms.

  vite-plugin-pages:gen routes: [] +0ms

</code></pre></details>
</summary>


<summary>
<code>pagesDir: 'frontend/pages'</code>

<details><pre><code>
    vite-plugin-pages:options {
  vite-plugin-pages:options   pagesDir: [],
  vite-plugin-pages:options   routeBlockLang: 'json5',
  vite-plugin-pages:options   root: '/home/xxx@xxx/frontend',
  vite-plugin-pages:options   extensions: [ 'vue', 'ts', 'js' ],
  vite-plugin-pages:options   importMode: 'async',
  vite-plugin-pages:options   exclude: [],
  vite-plugin-pages:options   syncIndex: true,
  vite-plugin-pages:options   replaceSquareBrackets: false,
  vite-plugin-pages:options   nuxtStyle: false,
  vite-plugin-pages:options   react: false,
  vite-plugin-pages:options   extensionsRE: /\.(vue|ts|js)$/,
  vite-plugin-pages:options   extendRoute: undefined,
  vite-plugin-pages:options   onRoutesGenerated: undefined,
  vite-plugin-pages:options   onClientGenerated: undefined
  vite-plugin-pages:options } +0ms
  vite-plugin-pages:pages Map(0) {} +0ms

  vite v2.3.8 dev server running at:

  > Local: https://localhost:3000/
  > Network: use `--host` to expose

  ready in 710ms.

  vite-plugin-pages:gen routes: [] +0ms
</code></pre></details>
</summary>



<summary>
<code>pagesDir: [{dir: 'frontend/pages', baseRoute: ''}]</code>

<details><pre><code>
  vite-plugin-pages:options {
  vite-plugin-pages:options   pagesDir: [],
  vite-plugin-pages:options   routeBlockLang: 'json5',
  vite-plugin-pages:options   root: '/home/xxx@xx/frontend',
  vite-plugin-pages:options   extensions: [ 'vue', 'ts', 'js' ],
  vite-plugin-pages:options   importMode: 'async',
  vite-plugin-pages:options   exclude: [],
  vite-plugin-pages:options   syncIndex: true,
  vite-plugin-pages:options   replaceSquareBrackets: false,
  vite-plugin-pages:options   nuxtStyle: false,
  vite-plugin-pages:options   react: false,
  vite-plugin-pages:options   extensionsRE: /\.(vue|ts|js)$/,
  vite-plugin-pages:options   extendRoute: undefined,
  vite-plugin-pages:options   onRoutesGenerated: undefined,
  vite-plugin-pages:options   onClientGenerated: undefined
  vite-plugin-pages:options } +0ms
  vite-plugin-pages:pages Map(0) {} +0ms

  vite v2.3.8 dev server running at:

  > Local: https://localhost:3000/
  > Network: use `--host` to expose

  ready in 718ms.

  vite-plugin-pages:gen routes: [] +0ms

</code></pre></details>
</summary>


Is `pagesDir` relative to the `root` option?

**Comment by Simonwep** [comment]
Awesome! That fixed it :) Thank you very much 👌
