### ISSUE TITLE
 Error: The following dependencies are imported but could not be resolved: virtual:generated-pages

### ISSUE THREAD

**Issue by VsevolodKurochka** [hannoeru/vite-plugin-pages#72]
Hi everyone! I have the next stack on my project: Vue 3, Vite, Typescript, Vite plugin pages for simplifying routing. And I needed to add a Storybook (https://storybook.js.org/blog/storybook-for-vite/) for my project.

After installing a Storybook I tried to start(npm run storybook) and got the error:
`info @storybook/vue3 v6.4.0-alpha.19
info
info => Loading presets
info => Using prebuilt manager
ERR! Error: The following dependencies are imported but could not be resolved:
ERR!
ERR!   virtual:generated-pages (imported by C:/Users/Dell/Desktop/projects/VTest/candidate-app-v2/src/main.ts)
ERR!
ERR! Are they installed?
ERR!     at optimizeDeps (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:66527:15)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERR!     at async runOptimize (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:70343:48)
ERR!     at async createServer (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\vite\dist\node\chunks\dep-0ed4fbc0.js:70372:9)
ERR!     at async Object.start (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\storybook-builder-vite\index.js:33:20)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\@storybook\core-server\dist\cjs\dev-server.js:123:28)
ERR!     at async buildDevStandalone (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\@storybook\core-server\dist\cjs\build-dev.js:112:31)
ERR!     at async buildDev (C:\Users\Dell\Desktop\projects\VTest\candidate-app-v2\node_modules\@storybook\core-server\dist\cjs\build-dev.js:154:5)
`

Does someone know how to fix it?

**Comment by brooksztb** [comment]
@VsevolodKurochka I was actually looking to use a similar tech stack as well, and I have been able to get things running in an application I was testing out. I am still running into some issues with the components not loading but I was able to resolve the issue with the `virtual:generated-pages` not being resolved. 

The key thing I found was that in the `storybook-builder-vite` docs they mention that "The builder will not read your vite.config.js file by default." So what I did was take all of the plugins that I was using in my `vite.vonfig.js` file and added them to my `.storybook/main.js` vite config.

This is what that config file looks like:
```js
const path = require('path')
const { default: vuePlugin } = require('@vitejs/plugin-vue')
const { default: pagesPlugin } = require('vite-plugin-pages/dist')
const { default: layoutPlugin } = require('vite-plugin-vue-layouts')
const { default: componentsPlugin } = require('vite-plugin-components')

module.exports = {
  async viteFinal(config, { configType }) {
    // customize the Vite config here
    config.resolve.alias['@/'] = `${path.resolve(__dirname, 'src')}/`
    config.plugins.push([
      vuePlugin({include: [/\.vue$/],}),
      pagesPlugin({extensions: ['vue'],}),
      layoutPlugin({}),
      componentsPlugin({extensions: ['vue'],})
    ])

    // return the customized config
    return config;
  },
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
  ],
  "core": {
    "builder": "storybook-builder-vite"
  }
}
```

This ended up resolving the loading issue and I was able to successfully build storybook after setting these configurations. I think whatever plugins you have set in your `vite.config.js` it needs to be matched exactly in the storybook config to work as expected.
