### ISSUE TITLE
Params `exclude`  does not work

### ISSUE THREAD

**Issue by fyeeme** [hannoeru/vite-plugin-pages#75]
vite.config.js

```js
    Pages({
      exclude: ['**/pages/authentic/*.vue']
    }),
```
but `.vue` in  `src/pages/authentic` folder is still generate route

![image](https://user-images.githubusercontent.com/6078758/128120680-c9286a5f-a115-4b75-96a7-190e897d7c31.png)

**Comment by duckbrain** [comment]
@fyeeme Is there a reason for closing this issue? It doesn't seem like it's fixed.

I've experienced this behavior too. It occurs when a new file is added inside of your pages directory, that also matches excludes. You can restart Vite to resolve it until the next new file is added.
