### ISSUE TITLE
router.push not work when page not loaded

### ISSUE THREAD

**Issue by transtone** [hannoeru/vite-plugin-pages#78]
https://github.com/transtone/vite-pages-router-bug

There is a dev mode bug.

It have a `go back login` button in the `about` page. It will route to the `login` page.
when click the button the first time, it won't go but reload the page. 
It only work in second or third click, when the page really loaded by vite.

**Comment by hannoeru** [comment]
That reload is triggered by Vite, not this plugin.

Add `@ant-design/icons-vue` to `optimizeDeps.include` in `vite.config.js` file can fix it.
