### ISSUE TITLE
Multiple paths in config

### ISSUE THREAD

**Issue by JohnCampionJr** [hannoeru/vite-plugin-pages#8]
My next step is to allow multiple paths in the config.   This will bring Vite-plugin-pages closer to config parity with Vite-plugin-components.    Is this a feature you'd be interested in?

**Comment by hannoeru** [comment]
Can you provide some use cases about that?

**Comment by JohnCampionJr** [comment]
For me, I like to store code in feature areas.  Was trying to come up with a way to do it like this

features/account/pages
features/users/pages
features/admin/pages

But I just realized thats going to get messy fast.  Would have to have some way to change the source dir / route path.  Might be a bit more involved than I first thought.  I had a simple prototype working but it won't cover this use case.

Could do this but seems awkward
features/account/pages/account
features/users/pages/users
features/admin/pages/admin

**Comment by hannoeru** [comment]
I think we only need to change `getPagesPath(options)`, use it to build some thing like is in the same folder, then pass to `generateRoutes`.

**Comment by hannoeru** [comment]
Sounds good, but that will be a little tricky as you are changing routes path, but still need to keep filePath to resolve components.
