### ISSUE TITLE
Generating a "Catch All" route

### ISSUE THREAD

**Issue by ackzell** [hannoeru/vite-plugin-pages#84]
Great plugin! Thanks for sharing :) 

The `[...all].vue` file didn't work for me, so I don't know if this is a matter of clarifying in the readme but after playing around with the plugin on a Vite project for generating a "catch all" route I ended up at creating a file named `_all(.*).vue`.

I guess important notes are:
* currently on `v0.17.3`
* `replaceSquareBrackets: true`
* `nuxtStyle: true`

See https://next.router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route and https://next.router.vuejs.org/guide/migration/index.html#removed-star-or-catch-all-routes for more info

![image](https://user-images.githubusercontent.com/601266/129611915-17ea681d-a00c-4a72-9eb7-189b1e534e5a.png)

Maybe that helps someone else / I can be corrected as to what is the better approach.

**Comment by hannoeru** [comment]
Cache all route with Nuxt style is `_.vue`

https://nuxtjs.org/docs/2.x/features/file-system-routing#unknown-dynamic-nested-routes
