### ISSUE TITLE
Support for optional paramaters?

### ISSUE THREAD

**Issue by OwenVey** [hannoeru/vite-plugin-pages#85]
Does this package support optional parameters? For example I can specify this route in Vue Router 4.x:
```js
{
  name: 'page-designer',
  path: '/page-designer/:id?',
  component: PageDesigner,
}
```

Ideally I'm trying to use the same component for both /page-designer as well as /page-designer/:id

**Comment by hannoeru** [comment]
You will need to edit generated routes, but why don't just wrap it to another component then use that component in both pages?

**Comment by wen403** [comment]
This problem is still unresolved, and I have encountered the same problem as before
