### ISSUE TITLE
A bug when using `<style>` without `scoped` in vue pages.

### ISSUE THREAD

**Issue by junaga** [hannoeru/vite-plugin-pages#87]
The problem is that pages inherit styling from each other based on directory structure, when `.vue` SFCs are written without the `<style scoped>`, and they do so inconsistently.

Take a look at the following [repo](https://github.com/junaga/vite-plugin-pages-bug)/src/pages (built from your examples).

## Explanation

The style rule for `p` written in `index.vue` is applied even in the `blog/today/index.vue` view. So far, not a problem. But the style rule for `h1` declared in `blog/index.vue` is applied only when `blog/today/index.vue` is being switched too by the **client-side router**. Not when we open the path directly from a **server with index fallback** configured. Because the previous page, was never initialized of course.

## My opinion

I think it would actually make sense to just disable `<style>` inheritance between _pages_. A directory of `.vue` _pages_ is kinda like a directory of `.html` pages written in vanilla. Every `vite-plugin-pages` page has it's own scoped `<style>` that by default only inherits into **imported components**. Not, into other pages.

I work with a few newbie folks, and they seemed really bothered about it, I have to agree. I think **this needs** to be changed.

Thank you for the awesome plugin, love.
Junaga

**Comment by hannoeru** [comment]
I think that is normal behavior, because of Vite's CSS code splitting, it only import css when  component loaded.

Disable css code split or load routes synchronize may solve this problem, but why don't just use scoped style?

**Comment by junaga** [comment]
Sorry, I don't understand the options you proposed, but thanks for trying. I picked up your plugin to save 3 days of the schedule and not learn `vue-router`.

## Not normal behavior

It's not just Vite, the `vite build` production bundle, renders a route **inconsistently**. If the user follows an internal link he gets a **different view** (different CSS), than if he had pasted the location in the browsers URL bar.

## Using `<style>`

Using `<style>` without `scoped` is totally justifiable. In a project where you sometimes want to apply styling to components dynamically. Imagine I have a table component that observes a document database in real time. I only pass the `path` when using it in a template. Depending on the _page_ it is used in, the font should be different. So I set a `<style>` in each page, and the component looks different on both routes. That's a completely normal [Vue practice](https://v3.vuejs.org/guide/single-file-component.html#introduction), and we actually work with it.

## Pages should not affect each other in any way.

Again, IMHO I think it just makes sense. This plugin is called `vite-plugin-pages` not `vite-plugin-views`. It is obviously a SPA, but everyone knows that. What's the point of recreating the mental model of _pages_ in a directory, if they do not behave like vanilla. Take a look at vite itself, it's just a static file server, so simple and elegant.

## How to solve the issue

I think, you could either include a "do not use `<style>`" warning in the readme, or build up this feature. Again, I think it makes perfect sense, and without it, I don't see how this plugin has a future.

thank you, and have a nice day

**Comment by junaga** [comment]
Probably not going to use any of your code in the future

thank you, and have a nice day
