### ISSUE TITLE
How to attach functions to `meta` properly?

### ISSUE THREAD

**Issue by ackzell** [hannoeru/vite-plugin-pages#88]
I've been trying to set up some breadcrumbs for my project.

Some of the solutions I've found involve adding a function that can resolve values to make the dynamic route present a label, for example:

```js
meta: {
          bcDynamic: true,
          // more values here...
          
          // once we have the user, we use this function to format the LinkText dnynamically,
          bcLinkText: user =>  user.name, 
          
          // This will be shown while Data is loading
          bcLoadingText: 'Loading Username...' 
        },
```

I was wondering where would be the best place to do such thing, given that the SFC portion for `<route>` supports only JSON, JSON5 and YAML

Best to do it on the `vite.config.js` with `extendRoute` ? From the docs:
> This is useful for augmenting your routes with extra data (e.g. route metadata).

The thing is, I would ideally want to keep any "breadcrumb config" (in this particular case) on the route itself and I am already using the `<route>` block for other stuff. 🤔 

Thanks!

**Comment by hannoeru** [comment]
You will need javascript to support function inside meta, so I think only route block will not works.
If you don't want configs split into two places, maybe you can set a value to `<route>` block then use `extendRoute` to transform it into a function.

**Comment by ackzell** [comment]
That is a good idea, thanks!
