### ISSUE TITLE
router-link not adding active class on parent

### ISSUE THREAD

**Issue by vincentccw** [hannoeru/vite-plugin-pages#93]
This is my current folder structure:
![image](https://user-images.githubusercontent.com/7234662/132952075-2e2f5070-95f1-450f-985b-fc3464779a6f.png)

And I have set up my navigation using router-link:
![image](https://user-images.githubusercontent.com/7234662/132952061-81f9cd2e-6e54-4424-a38c-d9472872f74f.png)

I'm currently on 5G mobility page and 'router-link-active' & 'router-link-exact-active' are added to 5G mobility link.
However, order capture does not display  'router-link-active' even though being the parent page of 5G mobility as shown below

![image](https://user-images.githubusercontent.com/7234662/132952066-4c974cd2-57cf-4616-bc35-d8d677a1242a.png)

Is there something need to be configured beforehand?

**Comment by hannoeru** [comment]
Can you provide a reproduction?

**Comment by vincentccw** [comment]
I have simulated the issue here, please have a look:
https://gitlab.com/vincentccw/vue-router-debug 

1. Install
pnpm install

2. Start dev
pnpm run dev

_Here is an extract on vue router online
Sourcer: https://newbedev.com/how-to-vuejs-router-link-active-style_
![image](https://user-images.githubusercontent.com/7234662/132977851-b56bac86-597e-4a04-a89a-5aea9ee573ba.png)

**Comment by hannoeru** [comment]
if its not a nested view, vite-plugin-pages will generate a flat routes, so active will not match, you can resolve the active status by yourself using route path.

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#unrelated-but-similiar-routes

**Comment by vincentccw** [comment]
alright, thanks for the recommendations
