### ISSUE TITLE
How to set the dynamic routing parameter is optional ？

### ISSUE THREAD

**Issue by xiaojieajie** [hannoeru/vite-plugin-pages#94]
How to set the dynamic routing parameter is optional ？

**Comment by hannoeru** [comment]
Yes

**Comment by xiaojieajie** [comment]
> Yes

I am asking how to use dynamic optional routing

**Comment by xiaojieajie** [comment]
In umi.js it is [id$]

**Comment by hannoeru** [comment]
Please read the readme before opening an issue...

https://github.com/hannoeru/vite-plugin-pages#file-system-routing

**Comment by xiaojieajie** [comment]
> Please read the readme before opening an issue...
> 
> https://github.com/hannoeru/vite-plugin-pages#file-system-routing

No optional route was found in the self-report material

**Comment by wen403** [comment]
How to solve it

**Comment by wen403** [comment]
@jbaubree Yes, but I can't create it
